const fs=require('fs'),path=require('path'),{randomUUID}=require('crypto');const root=path.resolve(__dirname,'..');
async function fixture(db){await db.exec(`
set check_function_bodies=off;create schema auth;create schema private;create role anon;create role authenticated;grant usage on schema public,private,auth to authenticated;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table public.profiles(id uuid primary key,display_name text);
create table public.teams(id uuid primary key,name text);
create table public.athletes(id uuid primary key,profile_id uuid,first_name text,last_name text,created_at timestamptz default now(),birth_date date);
create table public.seasons(id uuid primary key,team_id uuid,active boolean default true);
create table public.roster_memberships(season_id uuid,athlete_id uuid,active boolean default true);
create table public.team_memberships(team_id uuid,user_id uuid,athlete_id uuid,role text,active boolean default true,permissions jsonb default '{}');
create table public.athlete_guardians(athlete_id uuid,guardian_user_id uuid);
create table private.team_logins(user_id uuid);
create table private.team_goal_settings(team_id uuid primary key,enabled boolean not null default false,instructions text not null default '',categories jsonb not null default '[{"id":"academic","label":"Academic","count":5,"prompt":""},{"id":"wrestling","label":"Wrestling","count":5,"prompt":""}]',revision int not null default 1,updated_at timestamptz default now());
create table private.athlete_team_goals(team_id uuid,athlete_id uuid,entries jsonb not null default '{}',revision int not null default 1,updated_at timestamptz default now(),primary key(team_id,athlete_id));
create table private.wrestling_profiles(id uuid primary key,user_id uuid,athlete_profile_id uuid,name text,details jsonb default '{}',sharing jsonb default '{}',discoverable boolean default false,photo_path text,updated_at timestamptz default now());
create table private.wrestling_corners(profile_id uuid,member_id uuid,position int);
create table private.wrestling_follows(source_id uuid,target_id uuid,status text,created_at timestamptz default now());
create function public.is_team_staff(t uuid) returns boolean language sql stable security definer as $$select exists(select 1 from public.team_memberships where team_id=t and user_id=auth.uid() and active and role in ('head_coach','assistant_coach'))$$;
create function private.wrestling_profile_self(pid uuid) returns boolean language sql stable security definer as $$select exists(select 1 from private.wrestling_profiles p where p.id=pid and (p.user_id=auth.uid() or exists(select 1 from public.athletes a join public.team_memberships tm on tm.athlete_id=a.id and tm.user_id=auth.uid() and tm.role='athlete' and tm.active where a.profile_id=p.athlete_profile_id)))$$;
create function private.wrestling_profile_manager(pid uuid) returns boolean language sql stable security definer as $$select exists(select 1 from private.wrestling_profiles p where p.id=pid and (p.user_id=auth.uid() or exists(select 1 from public.athletes a join public.athlete_guardians ag on ag.athlete_id=a.id join public.team_memberships tm on tm.athlete_id=a.id and tm.user_id=ag.guardian_user_id and tm.role='parent_guardian' and tm.active where ag.guardian_user_id=auth.uid() and a.profile_id=p.athlete_profile_id)))$$;
create function private.wrestling_profile_teammates(a uuid,b uuid) returns boolean language sql as $$select false$$;
create function private.wrestling_profile_linked_child(a uuid,b uuid) returns boolean language sql as $$select false$$;
create function private.wrestling_role_badges(a uuid,b boolean) returns jsonb language sql as $$select '[]'::jsonb$$;
create function private.wrestling_spouse_card(a uuid,b boolean) returns jsonb language sql as $$select null::jsonb$$;
create function private.wrestling_profile_photo_source(a uuid,b boolean) returns jsonb language sql as $$select null::jsonb$$;
`);
await db.exec(fs.readFileSync(path.join(__dirname,'goals-profile-existing.sql'),'utf8'));await db.exec(fs.readFileSync(path.join(__dirname,'goals-existing-functions.sql'),'utf8'));await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',fs.readdirSync(path.join(root,'supabase/migrations')).find(x=>x.endsWith('athlete_goal_accomplishments_02040.sql'))),'utf8'));
await db.exec('set check_function_bodies=on');
const ids=Object.fromEntries(['coach','parent','athlete','mate','outsider','shared','team','other','a','b','c','season','otherseason','profile','portable','adultprofile'].map(k=>[k,randomUUID()]));
for(const key of ['coach','parent','athlete','mate','outsider','shared'])await db.query('insert into public.profiles values($1,$2)',[ids[key],key]);
await db.query("insert into public.teams values($1,'Example Girls Team'),($2,'Other team')",[ids.team,ids.other]);await db.query('insert into public.seasons(id,team_id) values($1,$2),($3,$4)',[ids.season,ids.team,ids.otherseason,ids.other]);
await db.query("insert into public.athletes(id,profile_id,first_name,last_name) values($1,$2,'Example','Athlete'),($3,null,'Example','Teammate'),($4,null,'Other','Athlete')",[ids.a,ids.portable,ids.b,ids.c]);
await db.query('insert into public.roster_memberships(season_id,athlete_id) values($1,$2),($1,$3),($4,$5)',[ids.season,ids.a,ids.b,ids.otherseason,ids.c]);
for(const [key,role,a,t] of [['coach','head_coach',null,ids.team],['parent','parent_guardian',ids.a,ids.team],['athlete','athlete',ids.a,ids.team],['mate','athlete',ids.b,ids.team],['outsider','athlete',ids.c,ids.other]])await db.query('insert into public.team_memberships(team_id,user_id,athlete_id,role) values($1,$2,$3,$4)',[t,ids[key],a,role]);
await db.query('insert into public.athlete_guardians values($1,$2)',[ids.a,ids.parent]);await db.query('insert into private.team_logins values($1)',[ids.shared]);await db.query("insert into private.wrestling_profiles(id,athlete_profile_id,name,discoverable) values($1,$2,'Example Athlete',true)",[ids.profile,ids.portable]);await db.query("insert into private.wrestling_profiles(id,user_id,name,discoverable) values($1,$2,'Other User',true)",[ids.adultprofile,ids.outsider]);
const as=async uid=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid||'']);await db.exec('set role authenticated');};
const req=async(action,data={})=>(await db.query('select public.team_goals_request($1,$2) r',[action,JSON.stringify({team_id:ids.team,...data})])).rows[0].r;
const view=()=>req('view',{athlete_id:ids.a});const profile=async(preview=false)=>(await db.query("select public.wrestling_profiles_request('view',$1) r",[JSON.stringify({id:ids.profile,preview})])).rows[0].r;
const save=async(p,entries,action='save',extra={})=>req(action,{athlete_id:ids.a,revision:p.revision,settings_revision:p.settings_revision,entries,...extra});
await as(ids.coach);let c=await req('context');await req('settings_save',{revision:c.revision,enabled:true,instructions:'Choose goals that challenge you.',categories:[{id:'academic',label:'Academic',count:1,prompt:''},{id:'wrestling',label:'Wrestling',count:1,prompt:''}]});await as(ids.athlete);
return {db,ids,as,req,view,profile,save};}
module.exports={fixture,root};
