const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
let init=fs.readFileSync(path.join(__dirname,'browser-fixture.js'),'utf8');
init=init.replace("if(name==='organization_governance')", "if(name==='wrestling_profiles_request')return window.profileRpc(args);if(name==='organization_governance')");
const fixtures=`
window.mtFixture={writes:[],seen:{},fail:null,lost:false,delay:0,readonly:false,m:null,history:[]};
const blank=()=>({agenda:[],roll:[{id:'adult-a',kind:'board',name:'Example Secretary',delegate:'',present:false,eligible:true},{id:'club-a',kind:'affiliate',name:'Historical Example Club',delegate:'',present:false,eligible:false}],minutes:'',guests:'',quorum:{rule:'',board_required:null,affiliate_required:null},motions:[],actions:[]});
window.governanceRpc=async q=>{const f=mtFixture;if(f.delay)await new Promise(r=>setTimeout(r,f.delay));
 if(q.action==='meeting_list')return {data:{can_create:!f.readonly,directory:[{id:'coach',name:'Example Adult'}],meetings:f.m?[{...f.m,minutes_version:f.m.version,can_edit:!f.readonly}]:[]},error:null};
 if(q.action==='meeting_detail'){let m=JSON.parse(JSON.stringify({...f.m,can_edit:!f.readonly,can_assign:!f.readonly,can_confidential:!f.readonly}));if(f.readonly)delete m.confidential_notes;return {data:m,error:null};}
 if(q.action==='meeting_history')return {data:JSON.parse(JSON.stringify(f.history)),error:null};
 f.writes.push(JSON.parse(JSON.stringify(q)));if(f.fail)return {error:{message:f.fail,code:f.code}};
 if(f.seen[q.request_id])return {data:f.seen[q.request_id],error:null};
 if(q.action==='meeting_create')f.m={id:'meeting-a',title:q.title,meeting_at:q.meeting_at,location:q.location,secretary_user_id:q.secretary_user_id,chair_user_id:q.chair_user_id,secretary:'Example Adult',chair:'',revision:1,version:0,status:'scheduled',document:blank(),confidential_notes:'',approval:null,minutes_label:'UNAPPROVED MINUTES'};
 else{if(q.revision!==f.m.revision)return {error:{message:'This meeting changed on another device. Reload the latest revision before saving.'}};f.m.revision++;
 if(q.action==='meeting_save'){f.m.document=JSON.parse(JSON.stringify(q.document));f.m.confidential_notes=q.confidential_notes;f.m.approval=null;f.m.minutes_label='UNAPPROVED MINUTES';}
 if(q.action==='meeting_start')f.m.status='active';if(q.action==='meeting_adjourn'){f.m.status='adjourned';f.m.adjourned_at=new Date().toISOString();}
 if(q.action==='meeting_approve'){f.m.approval={approved_on:q.approved_on,reference:q.reference};f.m.minutes_label='APPROVED MINUTES';}
 if(f.m.status==='adjourned'){f.m.version++;const snap=JSON.parse(JSON.stringify(f.m));delete snap.confidential_notes;f.history.unshift({version:f.m.version,reason:q.correction_reason||q.action,created_at:new Date().toISOString(),snapshot:snap});}}
 const out={id:f.m.id,revision:f.m.revision,minutes_version:f.m.version,status:f.m.status};f.seen[q.request_id]=out;if(f.lost){f.lost=false;return {error:{message:'Simulated lost response'}};}return {data:out,error:null};};
window.profileFixture={private:false};
window.profileRpc=async ({p_action,p_data})=>{const full={id:'profile-a',name:'Example Adult',manager:true,self:true,discoverable:!profileFixture.private,details:{bio:'PRIVATE-BIO',affiliation:'Example Club'},assigned_roles:[],corner:[],family_corner:[{id:'child-a',name:'PRIVATE-CHILD',details:{}}]};
 if(p_action==='mine')return {data:[full],error:null};if(p_action==='view')return {data:p_data.preview?(profileFixture.private?{id:'profile-a',discoverable:false,unavailable:true,details:{}}:{...full,details:{affiliation:'Example Club'},family_corner:undefined}):full,error:null};return {data:[],error:null};};
`;
const coach=()=>{fixture.session={user:{id:'coach',email:'coach@example.test'}};session=fixture.session;availableTeams=[{id:'team-a',name:'Example School Girls',organization_id:'org-a'},{id:'team-b',name:'Example State Girls',organization_id:'org-b'}];activeTeam=availableTeams[0];activeSeason={id:'season-a'};managedLogin=null;organizationMemberships=[{organization_id:'org-a',role:'organization_admin'}];teamMemberships=availableTeams.map(t=>({team_id:t.id,user_id:'coach',role:'head_coach',active:true}));organizationHeadingRows=[{id:'org-a',name:'Example School District'},{id:'org-b',name:'Example State Association'}];homeOrganizationId='org-a';homeOrganizationUser='coach';isStaff=actualIsStaff=isTeamAdmin=actualIsTeamAdmin=true;isManager=false;canAttendance=true;canWeighIn=true;viewMode='staff';show('authView',false);show('appView',true);applyRoleUI();setTab('more');};
async function main(){const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const results=[],pass=n=>{results.push(n);console.log('PASS',n)};
async function page(width){const p=await browser.newPage({viewport:{width,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.route('**/*',r=>r.request().url().includes('supabase-js')?r.fulfill({contentType:'text/javascript',body:'/* fixture */'}):r.abort());await p.evaluate(()=>{for(const kind of ['localStorage','sessionStorage']){const data=new Map();Object.defineProperty(window,kind,{value:{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k),clear:()=>data.clear(),key:i=>[...data.keys()][i]??null,get length(){return data.size}}})}Object.defineProperty(crypto,'randomUUID',{value:()=>Array.from({length:32},()=>Math.floor(Math.random()*16).toString(16)).join('')});});await p.evaluate(init);await p.evaluate(fixtures);await p.setContent(html,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>typeof WMMeetings!=='undefined');await p.waitForTimeout(100);await p.evaluate(coach);await p.evaluate(()=>WMOperations.open('org-a',null,'meetings'));await p.waitForSelector('#mtCreate');return {p,errors};}
async function create(p){await p.locator('#mtCreate').click();await p.locator('#mtTitle').fill('Spring board meeting');await p.locator('#mtAdult').check();await p.locator('#mtCreateForm button[type=submit]').click();await p.waitForSelector('#mtStart');}
try{const {p,errors}=await page(1024);await create(p);assert.match(await p.locator('#mtQuorum').innerText(),/not configured/);pass('Meeting created with assigned secretary and unconfigured quorum');
await p.locator('[data-m-add=agenda]').click();await p.locator('[data-m-path="agenda.0.topic"]').fill('Membership');await p.locator('[data-m-path="minutes"]').fill('Actual discussion notes');await p.locator('.mt-confidential summary').click();await p.locator('[data-m-path=confidential]').fill('EXECUTIVE ONLY');await p.locator('#mtSave').click();await p.waitForFunction(()=>document.getElementById('mtStatus').textContent==='Saved to organization.');await p.locator('#mtBack').click();await p.locator('[data-m-open]').click();await p.waitForSelector('#mtSave');assert.equal(await p.locator('[data-m-path=minutes]').inputValue(),'Actual discussion notes');pass('Server autosave survives closing and reopening the meeting');
await p.evaluate(()=>mtFixture.fail='Simulated offline');await p.locator('[data-m-path=minutes]').fill('Offline draft retained');await p.locator('#mtSave').click();await p.waitForFunction(()=>document.getElementById('mtStatus').textContent.includes('Not saved'));await p.locator('[data-ops-tab=home]').click();assert.equal(await p.locator('[data-m-path=minutes]').inputValue(),'Offline draft retained');assert.equal(await p.locator('#mtRoot').isVisible(),true);pass('Offline error is visible and navigation cannot silently discard edits');
await p.evaluate(()=>mtFixture.fail=null);await p.locator('#mtRetry').click();await p.waitForFunction(()=>document.getElementById('mtStatus').textContent==='Saved to organization.');let writes=await p.evaluate(()=>mtFixture.writes.filter(q=>q.document?.minutes==='Offline draft retained'));assert.equal(new Set(writes.map(q=>q.request_id)).size,1);pass('Retry reuses the same request after uncertain failure');
await p.evaluate(()=>{mtFixture.fail='Record the governing rule';mtFixture.code='P0001';});await p.locator('[data-m-path=minutes]').fill('Validation fails first');await p.locator('#mtSave').click();await p.waitForFunction(()=>document.getElementById('mtStatus').textContent.includes('Not saved'));await p.evaluate(()=>{mtFixture.fail=null;mtFixture.code=null;});await p.locator('[data-m-path=minutes]').fill('Corrected after validation error');await p.locator('#mtSave').click();await p.waitForFunction(()=>mtFixture.m.document.minutes==='Corrected after validation error');pass('A rejected validation can be corrected without discarding the draft');
await p.evaluate(()=>{mtFixture.lost=true;});await p.locator('[data-m-path=minutes]').fill('Accepted despite lost response');await p.locator('#mtSave').click();await p.waitForFunction(()=>document.getElementById('mtStatus').textContent.includes('Not saved'));let revision=await p.evaluate(()=>mtFixture.m.revision);await p.locator('#mtRetry').click();await p.waitForFunction(()=>document.getElementById('mtStatus').textContent==='Saved to organization.');assert.equal(await p.evaluate(()=>mtFixture.m.revision),revision);pass('Lost response retry does not duplicate an accepted save');
await p.evaluate(()=>mtFixture.delay=400);await p.locator('[data-m-path=minutes]').fill('First in-flight edit');await p.locator('#mtSave').click();await p.locator('[data-m-path=minutes]').fill('Second edit during save');await p.waitForFunction(()=>mtFixture.m.document.minutes==='Second edit during save');await p.waitForFunction(()=>document.getElementById('mtStatus').textContent==='Saved to organization.');await p.evaluate(()=>mtFixture.delay=0);pass('Edits typed during a save are queued and persist afterward');
await p.evaluate(()=>mtFixture.m.revision++);await p.locator('[data-m-path=minutes]').fill('Conflicting local text');await p.locator('#mtSave').click();await p.waitForFunction(()=>document.getElementById('mtStatus').textContent.includes('another device'));await p.locator('#mtReload').click();await p.waitForSelector('#mtDiscard');assert.equal(await p.locator('[data-m-path=minutes]').inputValue(),'Conflicting local text');await p.locator('#mtDiscard').click();await p.waitForFunction(()=>document.querySelector('[data-m-path=minutes]').value==='Second edit during save');pass('Revision conflicts preserve local edits and provide a saved-copy comparison');
await p.locator('[data-m-add=motions]').click();await p.locator('[data-m-path="motions.0.text"]').fill('Review the annual budget');await p.locator('[data-m-path="motions.0.mover"]').fill('Example Member');await p.locator('[data-m-add=actions]').click();await p.locator('[data-m-path="actions.0.task"]').fill('Obtain venue quote');await p.locator('#mtSave').click();await p.waitForFunction(()=>document.getElementById('mtStatus').textContent==='Saved to organization.');await p.screenshot({path:path.join(root,'validation/meetings-tablet.png')});await p.locator('#mtStart').click();await p.waitForSelector('#mtAdjourn');await p.locator('#mtAdjourn').click();await p.waitForSelector('#mtCorrect');assert.match(await p.locator('.mt-minutes').innerText(),/UNAPPROVED MINUTES/);assert(!await p.locator('.mt-minutes').innerText().then(t=>t.includes('EXECUTIVE ONLY')));pass('Adjournment shows unapproved minutes and separates restricted notes');
await p.locator('#mtCorrect').click();await p.locator('#mtCorrection').fill('Correct wording');await p.locator('[data-m-path=minutes]').fill('Corrected public notes');await p.locator('#mtDone').click();await p.waitForSelector('#mtCorrect');await p.locator('#mtHistory').click();assert((await p.locator('#mtRoot').innerText()).includes('Version 2'));await p.locator('#mtHistoryBack').click();await p.waitForSelector('#mtCorrect');pass('Corrections save a new minutes version with a reason');
await p.evaluate(()=>mtFixture.readonly=true);await p.locator('#mtBack').click();await p.locator('[data-m-open]').click();await p.waitForSelector('.mt-minutes');assert.equal(await p.locator('#mtCorrect').count(),0);assert(!(await p.locator('#mtRoot').innerText()).includes('EXECUTIVE ONLY'));pass('Reader view has no editor or executive notes');
await p.evaluate(()=>{mtFixture.readonly=false;WMOperations.close();});await p.evaluate(()=>WMProfiles.open());await p.waitForSelector('[data-wp-open="profile-a"]');await p.locator('[data-wp-open="profile-a"]').click();await p.waitForSelector('[data-wp-preview-id]');assert((await p.locator('#wpBody').innerText()).includes('PRIVATE-BIO'));await p.locator('[data-wp-preview-id]').click();await p.waitForFunction(()=>document.querySelector('[data-wp-preview-id]')?.getAttribute('aria-selected')==='true');assert(!(await p.locator('#wpBody').innerText()).includes('PRIVATE-BIO'));assert(!(await p.locator('#wpBody').innerText()).includes('PRIVATE-CHILD'));assert.equal(await p.locator('[data-wp-edit]').count(),0);assert.equal(await p.locator('[data-wp-affiliation]').isDisabled(),true);pass('What others see tab requests filtered profile and hides owner tools/private family fields');
await p.screenshot({path:path.join(root,'validation/profile-preview-tablet.png')});await p.locator('[data-wp-own]').click();await p.waitForSelector('[data-wp-edit]');assert((await p.locator('#wpBody').innerText()).includes('PRIVATE-BIO'));await p.evaluate(()=>profileFixture.private=true);await p.locator('[data-wp-preview-id]').click();await p.waitForFunction(()=>document.getElementById('wpBody').textContent.includes('This profile is private'));assert.equal(await p.locator('#wpBody [role=tab]').count(),2);pass('Private profile preview explains visibility and retains both tabs');assert.deepEqual(errors,[]);await p.close();
const phone=await page(390);await create(phone.p);assert(await phone.p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await phone.p.screenshot({path:path.join(root,'validation/meetings-phone.png')});await phone.p.evaluate(()=>{WMOperations.close();WMProfiles.open();});await phone.p.waitForSelector('[data-wp-open="profile-a"]');await phone.p.locator('[data-wp-open="profile-a"]').click();await phone.p.locator('[data-wp-preview-id]').click();await phone.p.waitForFunction(()=>document.querySelector('[data-wp-preview-id]')?.getAttribute('aria-selected')==='true');assert(await phone.p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await phone.p.screenshot({path:path.join(root,'validation/profile-preview-phone.png')});assert.deepEqual(phone.errors,[]);pass('Phone meeting and profile tabs fit at 390px with no script errors');await phone.p.close();
}finally{await browser.close();}fs.writeFileSync(path.join(root,'validation/meetings-browser.json'),JSON.stringify({passed:results.length,tests:results},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
