create table private.organization_meetings (
id uuid default gen_random_uuid() not null,
organization_id uuid not null,
title text not null,
meeting_at timestamp with time zone not null,
location text default ''::text not null,
status text default 'scheduled'::text not null,
visibility text default 'affiliates'::text not null,
agenda jsonb default '[]'::jsonb not null,
notes text default ''::text not null,
chair_user_id uuid,
secretary_user_id uuid,
quorum_percent numeric(5,2) default 50.00 not null,
started_at timestamp with time zone,
adjourned_at timestamp with time zone,
minutes_published_at timestamp with time zone,
minutes_snapshot jsonb,
revision integer default 1 not null,
created_by uuid not null,
updated_by uuid not null,
created_at timestamp with time zone default now() not null,
updated_at timestamp with time zone default now() not null,
CHECK ((jsonb_typeof(agenda) = 'array'::text)),
FOREIGN KEY (chair_user_id) REFERENCES profiles(id) ON DELETE SET NULL,
FOREIGN KEY (created_by) REFERENCES profiles(id),
FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
PRIMARY KEY (id),
CHECK (((quorum_percent > (0)::numeric) AND (quorum_percent <= (100)::numeric))),
FOREIGN KEY (secretary_user_id) REFERENCES profiles(id) ON DELETE SET NULL,
CHECK ((status = ANY (ARRAY['scheduled'::text, 'active'::text, 'adjourned'::text, 'cancelled'::text]))),
CHECK (((length(TRIM(BOTH FROM title)) >= 1) AND (length(TRIM(BOTH FROM title)) <= 200))),
FOREIGN KEY (updated_by) REFERENCES profiles(id),
CHECK ((visibility = ANY (ARRAY['leaders'::text, 'affiliates'::text, 'members'::text])))
);

create table private.organization_meeting_attendance (
id uuid default gen_random_uuid() not null,
meeting_id uuid not null,
participant_kind text not null,
participant_id uuid not null,
display_name text not null,
delegate_user_id uuid,
present boolean default false not null,
checked_in_by uuid,
checked_in_at timestamp with time zone,
created_at timestamp with time zone default now() not null,
UNIQUE (meeting_id, participant_kind, participant_id),
FOREIGN KEY (checked_in_by) REFERENCES profiles(id) ON DELETE SET NULL,
FOREIGN KEY (delegate_user_id) REFERENCES profiles(id) ON DELETE SET NULL,
CHECK ((participant_kind = ANY (ARRAY['board'::text, 'affiliate'::text]))),
FOREIGN KEY (meeting_id) REFERENCES private.organization_meetings(id) ON DELETE CASCADE,
PRIMARY KEY (id)
);

create table private.organization_meeting_versions (
id bigint generated always as identity not null,
meeting_id uuid not null,
version integer not null,
reason text default ''::text not null,
snapshot jsonb not null,
created_by uuid not null,
created_at timestamp with time zone default now() not null,
FOREIGN KEY (created_by) REFERENCES profiles(id),
FOREIGN KEY (meeting_id) REFERENCES private.organization_meetings(id) ON DELETE CASCADE,
UNIQUE (meeting_id, version),
PRIMARY KEY (id)
);
