const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite'),{root,fixture}=require('./reactions-fixture.cjs');
async function main(){const db=new PGlite(),{ids,as,call,list,set}=await fixture(db),tests=[],pass=s=>{tests.push(s);console.log('PASS',s)};
 let p=await set('wrestling');assert.equal(p.messages[0].reactions[0].count,1);assert.equal(p.messages[0].reactions[0].mine,true);await set('wrestling');assert.equal((await list()).messages[0].reactions[0].count,1);await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from private.message_reaction_events')).rows[0].n,1);pass('A saved reaction and repeated request produce one selection and one event');
 await as(ids.mate);await set('wrestling');p=await list();assert.equal(p.messages[0].reactions[0].count,2);assert.equal(p.messages[0].reactions[0].people.length,2);await set('fire');assert.equal((await list()).messages[0].reactions.length,2);await set(null);p=await list();assert.equal(p.messages[0].reactions.length,1);assert.equal(p.messages[0].reactions[0].mine,false);pass('Members see shared counts; changing/removing affects only their own reaction');
 await as(ids.user);await assert.rejects(set('arbitrary'),/available reaction/);await assert.rejects(call('set',{message_id:ids.message}),/Choose a reaction/);await assert.rejects(call('set',{message_id:ids.removed,reaction:'fire'}),/unavailable/);await assert.rejects(call('set',{message_id:ids.simulated,reaction:'fire'}),/unavailable/);pass('Only fixed reactions and active real messages are accepted');
 await assert.rejects(call('list',{message_ids:[ids.otherMessage]}),/belong/);await assert.rejects(call('set',{message_id:ids.otherMessage,reaction:'fire'}),/unavailable/);await as(ids.outsider);await assert.rejects(list(),/access required/);pass('Thread membership and message ownership prevent cross-team reads and writes');
 await as(ids.mirror);assert.equal((await list()).can_react,false);await assert.rejects(set('heart'),/not allowed/);pass('Read-only guardian mirrors can view but cannot react');
 await db.exec('reset role');await db.query('insert into public.communication_blocks values($1,$2,$3)',[ids.team,ids.user,ids.mate]);await as(ids.user);assert.equal((await list()).can_react,false);await assert.rejects(set('fire'),/not allowed/);await db.exec('reset role');await db.exec('delete from public.communication_blocks');pass('Direct-chat blocking prevents reactions');
 await db.query('update public.fixture_access set capability=false where user_id=$1',[ids.minor]);await as(ids.minor);await assert.rejects(set('heart'),/not allowed/);await as(ids.user);await assert.rejects(set('heart'),/not allowed/);await db.exec('reset role');await db.query('update public.fixture_access set capability=true where user_id=$1',[ids.minor]);pass('Current parent restrictions prevent both sides from reacting in a restricted direct chat');
 await db.query('update public.fixture_access set active=false where user_id=$1',[ids.user]);await as(ids.user);await assert.rejects(list(),/access required/);await db.exec('reset role');await db.query('update public.fixture_access set active=true where user_id=$1',[ids.user]);await db.query('update public.communication_thread_members set left_at=now() where user_id=$1',[ids.user]);await as(ids.user);await assert.rejects(set('clap'),/access required/);await db.exec('reset role');await db.query('update public.communication_thread_members set left_at=null where user_id=$1',[ids.user]);pass('Revoked team access and removed thread members cannot use reactions');
 await db.query('update public.communication_threads set archived_at=now() where id=$1',[ids.thread]);await as(ids.user);await assert.rejects(list(),/unavailable/);await db.exec('reset role');await db.query('update public.communication_threads set archived_at=null,is_safety_test=true where id=$1',[ids.thread]);await as(ids.user);await assert.rejects(list(),/unavailable/);pass('Archived conversations and safety simulations reject reactions');
 await as(ids.shared);await assert.rejects(list(),/Personal account/);await as(null);await assert.rejects(list(),/Personal account/);await as(ids.user);await assert.rejects(db.query('select * from private.message_reactions'),/permission denied/);await assert.rejects(db.query("select private.message_reactions_request('list','{}')"),/permission denied/);await db.exec('reset role;set role anon');await assert.rejects(db.query("select public.message_reactions_request('list','{}')"),/permission denied/);pass('Shared/anonymous accounts and direct private-table/helper access denied');
 fs.writeFileSync(path.join(root,'validation/reactions-db.json'),JSON.stringify({passed:tests.length,tests},null,2));await db.close();}
 main().catch(e=>{console.error(e);process.exit(1)});
