'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'src/schedule-badges.js'),'utf8'),bundle=fs.readFileSync(path.join(root,'index.html'),'utf8');
const begin=bundle.indexOf('async function loadSchedule(){'),end=bundle.indexOf('\nfunction dateKeyLocal',begin);
assert(begin>0&&end>begin);assert(bundle.includes(source));
const loader=bundle.slice(begin,end),passed=[],pass=s=>{passed.push(s);console.log('PASS',s);};
const BASE=Date.parse('2026-09-29T15:00:00Z'),iso=n=>new Date(n).toISOString();
const event=(id,n=BASE)=>({id,team_id:'team-a',title:'Synthetic Practice',event_type:'practice',starts_at:iso(BASE+86400000),updated_at:iso(n)});
function env(store=new Map()){
 const c={session:{user:{id:'coach'}},activeTeam:{id:'team-a'},activeSeason:{id:'season-a'},scheduleRows:[],store,errors:[],renders:0,badge:0,orgCalls:[],queries:[],document:{hidden:false},visible:false};
 c.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v)};c.window=c;
 c.$=()=>({classList:{contains:()=>!c.visible}});
 c.renderSchedule=()=>{c.renders++;};c.renderUpcomingHome=c.renderAttention=()=>{};
 c.message=s=>c.errors.push(s);c.updateBottomNavBadges=()=>{c.badge=c.WMScheduleBadges.count();};
 c.client={from:name=>{assert.equal(name,'team_events');const q={select(){return this;},eq(k,v){q.team=v;return this;},order(){return this;},then(resolve,reject){c.queries.push(q.team);Promise.resolve().then(()=>c.response()).then(resolve,reject);}};return q;}};
 c.response=async()=>({data:c.rows||[],error:null});c.WMOperations={calendar:async team=>{c.orgCalls.push(team);return c.orgRows||[];}};
 vm.createContext(c);vm.runInContext(source,c);vm.runInContext(loader,c);return c;
}
const key=(user='coach',team='team-a')=>`wm_nav_seen_schedule_${user}_${team}`;
const changeTeam=(c,id)=>{c.activeTeam={id};c.WMScheduleBadges.reset();c.scheduleRows=[];};
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
(async()=>{
 const c=env();c.rows=Array.from({length:74},(_,i)=>event('p'+i));
 assert.equal(c.rows.filter(r=>Date.parse(r.updated_at)>0).length,74,'negative control reproduces old code');
 c.updateBottomNavBadges();assert.equal(c.store.size,0);await c.loadSchedule();assert.equal(c.badge,0);assert.equal(c.store.get(key()),String(BASE));
 pass('74 existing practices establish a quiet baseline only after the first successful response');
 c.rows=[...c.rows.map((r,i)=>i===0?event(r.id,BASE+1000):r),event('new',BASE+2000)];await c.loadSchedule();assert.equal(c.badge,2);await c.loadSchedule();assert.equal(c.badge,2);
 c.WMScheduleBadges.markSeen();assert.equal(c.WMScheduleBadges.count(),0);assert.equal(c.store.get(key()),String(BASE+2000));
 pass('Later additions and edits count until acknowledged; refresh does not erase unread updates');
 changeTeam(c,'team-b');c.rows=[event('b',BASE+3000)];await c.loadSchedule();assert.equal(c.badge,0);const bSeen=c.store.get(key('coach','team-b'));
 changeTeam(c,'team-a');c.rows=[event('a',BASE+2000)];await c.loadSchedule();assert.equal(c.badge,0);assert.equal(c.store.get(key('coach','team-b')),bSeen);
 pass('Team A to B to A retains separate baselines instead of counting each team season again');
 const restored=env(c.store);restored.rows=[event('a',BASE+2000)];await restored.loadSchedule();assert.equal(restored.badge,0);
 const fresh=env();fresh.rows=restored.rows;await fresh.loadSchedule();assert.equal(fresh.badge,0);
 c.session={user:{id:'other'}};c.WMScheduleBadges.reset();c.rows=[event('a',BASE+4000)];await c.loadSchedule();assert.equal(c.badge,0);assert.equal(c.store.get(key()),String(BASE+2000));
 pass('Reload, a fresh device and a different personal account do not inherit a false practice count');
 const legacy=env(new Map([[key(),String(BASE)]]));legacy.rows=[event('old'),event('edited',BASE+3000)];await legacy.loadSchedule();assert.equal(legacy.badge,1);
 pass('An existing valid last-viewed value is preserved, including its genuinely newer rows');
 const empty=env();await empty.loadSchedule();assert.equal(empty.store.get(key()),'0');empty.rows=[event('first')];await empty.loadSchedule();assert.equal(empty.badge,1);
 pass('A successfully loaded empty schedule is initialized; its first later event is still new');
 const failed=env();failed.response=async()=>({error:{message:'Synthetic network failure'}});failed.WMScheduleBadges.markSeen();await failed.loadSchedule();assert.equal(failed.store.size,0);assert.equal(failed.renders,0);
 failed.response=async()=>({data:[event('recovered')]});await failed.loadSchedule();assert.equal(failed.badge,0);
 pass('Failed loads and opening before data arrives cannot create or advance a last-viewed marker');
 const race=env(),old=deferred();race.response=()=>old.promise;const a=race.loadSchedule();await Promise.resolve();changeTeam(race,'team-b');old.resolve({data:[event('wrong-team')]});await a;
 assert.equal(race.renders,0);assert.equal(race.store.size,0);assert.deepEqual(race.orgCalls,[]);
 pass('A team switch before the database reply rejects old rows before calling the organization calendar');
 const org=env(),orgWait=deferred();org.WMOperations.calendar=()=>orgWait.promise;org.rows=[event('old')];const orgFlight=org.loadSchedule();await new Promise(r=>setImmediate(r));changeTeam(org,'team-b');orgWait.resolve([]);await orgFlight;assert.equal(org.renders,0);assert.equal(org.store.size,0);
 pass('A team switch while organization dates are loading also rejects the entire stale response');
 const overlap=env(),older=deferred();overlap.response=()=>older.promise;const f=overlap.loadSchedule();await Promise.resolve();overlap.response=()=>({data:[event('newer')]});await overlap.loadSchedule();older.resolve({data:[event('older')]});await f;assert.equal(overlap.scheduleRows[0].id,'newer');assert.equal(overlap.renders,1);
 pass('Overlapping refreshes keep the newest requested response, not the last response to arrive');
 const cycle=env(),ticket=cycle.WMScheduleBadges.begin();changeTeam(cycle,'team-b');changeTeam(cycle,'team-a');assert.equal(cycle.WMScheduleBadges.accept(ticket,[event('old')]),false);
 const ticket2=cycle.WMScheduleBadges.begin();cycle.activeSeason={id:'another-season'};assert.equal(cycle.WMScheduleBadges.valid(ticket2),false);
 cycle.activeSeason={id:'season-a'};const ticket3=cycle.WMScheduleBadges.begin();cycle.WMScheduleBadges.reset();assert.equal(cycle.WMScheduleBadges.valid(ticket3),false);
 pass('A to B to A, season changes and reset fence out earlier requests even when IDs return');
 const account=env(),lateError=deferred();account.response=()=>lateError.promise;const errFlight=account.loadSchedule();await Promise.resolve();account.session={user:{id:'another'}};lateError.resolve({error:{message:'Previous account error'}});await errFlight;assert.deepEqual(account.errors,[]);assert.equal(account.store.size,0);
 pass('Late results and errors from a previous account do not alter the current account UI or storage');
 const visible=env(new Map([[key(),String(BASE)]]));visible.visible=true;visible.rows=[event('edited',BASE+1000)];await visible.loadSchedule();assert.equal(visible.badge,0);assert.equal(visible.store.get(key()),String(BASE+1000));
 visible.visible=false;visible.rows=[event('edited',BASE+2000)];await visible.loadSchedule();assert.equal(visible.badge,1);visible.visible=true;visible.document.hidden=true;await visible.loadSchedule();assert.equal(visible.badge,1);
 pass('Successful visible Schedule loads acknowledge loaded changes; hidden tabs and hidden documents do not');
 const storage=env();storage.localStorage={getItem(){throw Error('storage blocked');},setItem(){throw Error('quota');}};storage.rows=[event('first')];await storage.loadSchedule();assert.equal(storage.badge,0);storage.rows=[event('newer',BASE+1000)];await storage.loadSchedule();assert.equal(storage.badge,1);storage.WMScheduleBadges.markSeen();assert.equal(storage.WMScheduleBadges.count(),0);assert.deepEqual(storage.errors,[]);
 for(const raw of ['NaN','-1','', 'Infinity']){const x=env(new Map([[key(),raw]]));x.rows=[event('first')];await x.loadSchedule();assert.equal(x.badge,0);}
 pass('Disabled/quota-limited storage uses a session fallback; corrupt numeric markers are re-baselined safely');
 const mixed=env();mixed.rows=[{...event('legacy'),updated_at:null,created_at:iso(BASE)},{id:'invalid',updated_at:'not a date'}];mixed.orgRows=[event('org',BASE+3000)];await mixed.loadSchedule();assert.equal(mixed.badge,0);assert.equal(mixed.store.get(key()),String(BASE+3000));mixed.orgRows=[event('org',BASE+4000)];await mixed.loadSchedule();assert.equal(mixed.badge,1);
 pass('Existing organization rows and created-at fallback join the initial baseline without date parsing errors');
 const external=env(new Map([[key(),String(BASE)]]));external.rows=[event('edited',BASE+1000)];await external.loadSchedule();assert.equal(external.badge,1);external.store.set(key(),String(BASE+1000));assert.equal(external.WMScheduleBadges.count(),0);
 assert(!source.includes('Date.now('));assert(!source.includes('localStorage.clear'));assert(!source.includes('removeItem'));
 pass('Existing shared-browser acknowledgements are observed; no device clock or bulk storage clearing is used');
 assert(bundle.includes("window.WMScheduleBadges.reset();scheduleRows=[];setNavBadge('schedule',0,'unseen schedule changes');"));
 let scripts=0;for(const m of bundle.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)){new vm.Script(m[1]);scripts++;}
 pass(`All ${scripts} inline scripts parse and exact source is embedded without native or server changes`);
 fs.writeFileSync(path.join(root,'validation/schedule-badges.json'),JSON.stringify({passed,engine:'Node VM executing exact embedded component and loadSchedule with synthetic responses',productionDataChanged:false},null,2));
})().catch(e=>{console.error(e);process.exit(1);});
