const fs=require('fs'),assert=require('node:assert/strict'),path=require('path');
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const root=path.resolve(__dirname,'..');
async function main(){
 const db=new PGlite(); await db.exec(fs.readFileSync(path.join(__dirname,'structure-fixture.sql'),'utf8'));
 const ids={admin:'10000000-0000-0000-0000-000000000001',adult:'10000000-0000-0000-0000-000000000002',minor:'10000000-0000-0000-0000-000000000003',shared:'10000000-0000-0000-0000-000000000004',outsider:'10000000-0000-0000-0000-000000000005',org:'20000000-0000-0000-0000-000000000001',other:'20000000-0000-0000-0000-000000000002',team:'30000000-0000-0000-0000-000000000001',external:'30000000-0000-0000-0000-000000000002',athlete:'40000000-0000-0000-0000-000000000001'};
 for(const k of ['admin','adult','minor','shared','outsider'])await db.query('insert into public.profiles values($1,$2)',[ids[k],k]);
 await db.query("insert into public.organizations(id,name) values($1,'Test organization'),($2,'Other tenant')",[ids.org,ids.other]);
 await db.query("insert into public.organization_memberships values($1,$2,'organization_admin'),($1,$3,'assistant_coach'),($4,$5,'organization_admin')",[ids.org,ids.admin,ids.adult,ids.other,ids.outsider]);
 await db.query("insert into public.teams values($1,$2,'Team'),($3,$4,'External team')",[ids.team,ids.org,ids.external,ids.other]);
 await db.query("insert into public.athletes values($1,current_date-interval '15 years')",[ids.athlete]);
 await db.query("insert into public.team_memberships(team_id,user_id,role,athlete_id) values($1,$2,'athlete',$3),($1,$4,'manager',null)",[ids.team,ids.minor,ids.athlete,ids.shared]);
 await db.query('insert into private.team_logins values($1)',[ids.shared]);
 await db.query("insert into private.organization_affiliates(organization_id,name) values($1,'Historical Club')",[ids.org]);
 await db.query("insert into private.organization_positions(organization_id,title,access_role) values($1,'Female Athlete Rep','board')",[ids.org]);
 const migration=fs.readdirSync(path.join(root,'supabase/migrations')).find(x=>x.endsWith('_organization_structure_02036.sql'));
 await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',migration),'utf8'));
 // Use the actual public wrapper from production (the migration deliberately preserves it).
 await db.exec("create or replace function public.organization_governance(p_request jsonb) returns jsonb language sql set search_path='' as $$select private.organization_governance(p_request)$$");
 const results=[];const pass=n=>{results.push(n);console.log('PASS',n)};
 async function as(user){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user||'']);await db.exec('set role authenticated');}
 const req=async q=>(await db.query('select public.organization_governance($1::jsonb) result',[JSON.stringify({organization_id:ids.org,request_id:require('crypto').randomUUID(),...q})])).rows[0].result;
 const denied=async(q,pattern)=>{await assert.rejects(()=>req(q),pattern);};
 await as(ids.admin);let c=await req({action:'context'});
 assert.equal(c.affiliates[0].voting_review,'unreviewed');assert.equal(c.affiliates[0].voting_eligible,false);assert.equal(c.positions[0].assignment_enabled,false);pass('Existing directory preserved but unreviewed; athlete representative deferred');
 assert.deepEqual(c.directory.map(x=>x.name).sort(),['admin','adult']);pass('Adult selector excludes minor, shared login and unrelated tenant');
 const create={action:'save_position',title:'Secretary',user_id:ids.adult,confirm_adult:true};
 await denied({...create,confirm_adult:false},/Confirm/);await denied({...create,user_id:ids.minor},/adult/);await denied({...create,user_id:ids.outsider},/adult/);pass('Server rejects unconfirmed, minor and cross-tenant assignments');
 const pos=await req(create);const second=await req({...create,title:'Treasurer'});assert.notEqual(pos.id,second.id);pass('One adult can hold multiple posts');
 const retryRequest={action:'save_affiliate',title:'Retry club',request_id:require('crypto').randomUUID()};
 const retry1=await req(retryRequest),retry2=await req(retryRequest);assert.deepEqual(retry1,retry2);await denied({...retryRequest,title:'Different'},/different content/);pass('Save replay is idempotent and changed-payload replay is rejected');
 const presetRequest={action:'add_presets',preset:'school',request_id:require('crypto').randomUUID()};
 const seeded=await req(presetRequest);assert.equal(seeded.added,7);assert.deepEqual(await req(presetRequest),seeded);assert.equal((await req({action:'add_presets',preset:'school'})).added,0);pass('Templates create vacant posts once without permissions');
 await denied({...create,id:pos.id},/Reload/);await denied({...create,id:pos.id,revision:0},/changed/);pass('Missing and stale revisions rejected');
 await denied({...create,id:pos.id,revision:1,access_role:'president'},/confirm.*permissions/i);pass('Explicit access grant confirmation required');
 let p=await req({...create,id:pos.id,revision:1,access_role:'board',confirm_access:true});
 c=await req({action:'context'});assert.equal(c.positions.find(x=>x.id===p.id).access_role,'board');pass('Confirmed access permission stored independently of title');
 await denied({...create,id:c.positions.find(x=>!x.assignment_enabled).id,revision:c.positions.find(x=>!x.assignment_enabled).revision},/deferred/);pass('Athlete template cannot be assigned or renamed around restriction');
 await req({...create,id:second.id,revision:1,parent_position_id:pos.id});
 await denied({...create,id:pos.id,revision:p.revision,parent_position_id:second.id},/cycle/);pass('Hierarchy cycle rejected');
 await req({action:'archive_position',id:pos.id,revision:p.revision});await denied({action:'restore_position',id:pos.id,revision:p.revision},/changed/);pass('Archive and restore require latest revision');
 let aff=await req({action:'save_affiliate',title:'New club'});
 await denied({action:'save_affiliate',id:aff.id,revision:1,title:'New club',voting_review:'eligible'},/confirmed/);
 await denied({action:'save_affiliate',id:aff.id,revision:1,title:'New club',membership_review:'confirmed',voting_review:'eligible'},/governing/);pass('Voting eligibility requires separate membership review and rule record');
 await denied({action:'save_affiliate',title:'External',linked_team_id:ids.external},/approve/);await denied({action:'save_affiliate',title:'External',linked_organization_id:ids.other},/administer/);pass('Unapproved team and unrelated organization links rejected');
 aff=await req({action:'save_affiliate',id:aff.id,revision:1,title:'New club',membership_review:'confirmed',voting_review:'eligible',review_note:'Configured rule for test only',linked_team_id:ids.team});
 aff=await req({action:'archive_affiliate',id:aff.id,revision:aff.revision});aff=await req({action:'restore_affiliate',id:aff.id,revision:aff.revision});
 c=await req({action:'context'});let a=c.affiliates.find(x=>x.id===aff.id);assert.equal(a.status,'active');assert.equal(a.membership_review,'unreviewed');assert.equal(a.voting_eligible,false);pass('Reactivation retains identity and resets eligibility review');
 const history=await req({action:'history',id:a.id,entity_kind:'affiliate'});assert.equal(history.length,4);assert.equal(history[2].snapshot.voting_eligible,true);pass('Immutable revision history preserves earlier affiliation states');
 for(const act of ['save_meeting','open_motion','cast_vote','save_delegate'])await denied({action:act},/not enabled/);pass('Incomplete meeting and voting APIs unavailable');
 await as(ids.adult);c=await req({action:'context'});assert.equal(c.can_manage_structure,false);assert.deepEqual(c.directory,[]);
 await denied({action:'save_position',title:'Chairman'},/administrator/);await denied({action:'history',entity_kind:'affiliate',id:aff.id},/administrator/);pass('Nonadministrator can read limited structure but cannot write or read history');
 await as(ids.outsider);await denied({action:'context'},/access/);pass('Tenant separation enforced');
 await as(ids.shared);await denied({action:'context'},/personal/);await as(null);await denied({action:'context'},/personal/);pass('Shared and unauthenticated accounts rejected');
 await as(ids.admin);await assert.rejects(()=>db.query('select * from private.organization_structure_versions'),/permission denied/);await assert.rejects(()=>db.query('select private.gov_structure_action(\'{}\')'),/does not exist|permission denied/);pass('No direct table access');
 await db.exec('reset role');const unchanged=(await db.query('select count(*)::int n from public.organization_memberships')).rows[0].n;assert.equal(unchanged,3);pass('No organization memberships or team management changed');
 fs.mkdirSync(path.join(root,'validation'),{recursive:true});fs.writeFileSync(path.join(root,'validation','structure-db.json'),JSON.stringify({engine:'PGlite/PostgreSQL',tests:results,passed:results.length},null,2));
 await db.close();
}
main().catch(e=>{console.error(e);process.exit(1)});
