const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{randomUUID}=require('crypto'),{PGlite}=require('@electric-sql/pglite'),{fixture,root}=require('./team-plan-fixture.cjs');
(async()=>{
 const db=new PGlite(),f=await fixture(db),{ids,as,plan,resource,apply,pilot}=f,tests=[];
 const pass=s=>{tests.push(s);console.log('PASS',s);};
 let p=await plan();assert.equal(p.plan,'free');assert.equal(p.access_source,'pilot');assert.equal(p.purchases_available,false);
 await resource('equipment_add',{title:'Singlet · medium',quantity:3,notes:'Synthetic record'});assert.equal((await resource('equipment_list')).write,true);pass('Pilot includes inventory tools without creating a paid subscription or checkout');
 await pilot(false);await as(ids.coach);p=await plan();assert.equal(p.full_access,false);assert.equal(p.access_source,'free');
 assert.equal((await resource('equipment_list')).rows.length,1);assert.equal((await resource('equipment_list')).write,false);
 await assert.rejects(()=>resource('equipment_add',{title:'Blocked',quantity:1}),/Full Year/);pass('Free teams keep inventory reads but cannot write after pilot access ends');
 assert.equal(await apply(),1);assert.equal(await apply(),1);await as(ids.coach);assert.equal((await plan()).plan,'full_year');
 await assert.rejects(()=>apply({status:'revoked'}),/Event ID/);await assert.rejects(()=>apply({event:'stale',revision:0}),/Subscription changed/);
 await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from private.team_subscription_events')).rows[0].n,1);pass('Verified events are idempotent; changed replays and stale revisions roll back');
 await db.exec("set timezone='Pacific/Honolulu'");assert.equal(await apply(),1);await db.exec("set timezone='UTC'");pass('Equivalent billing retries remain idempotent across database time zones');
 await db.query("insert into public.team_memberships(team_id,user_id,role) values($1,$2,'head_coach')",[ids.other,ids.coach]);
 await as(ids.coach);assert.equal((await plan(ids.other)).plan,'free');
 await assert.rejects(()=>apply({team:ids.other,event:'copy'}),/another team/);await as(ids.coach);
 await assert.rejects(()=>resource('equipment_add',{team:ids.other,title:'Blocked copy',quantity:1}),/Full Year/);pass('One coach with two teams cannot reuse the first team subscription');
 await db.exec('reset role');await db.query("update public.teams set name='Renamed Team' where id=$1",[ids.team]);
 await db.query("insert into public.team_memberships(team_id,user_id,role) values($1,$2,'head_coach')",[ids.team,ids.outsider]);
 await db.query('update public.team_memberships set active=false where team_id=$1 and user_id=$2',[ids.team,ids.coach]);await as(ids.coach);await assert.rejects(()=>plan(),/access required/);
 await as(ids.outsider);assert.equal((await plan()).team_name,'Renamed Team');assert.equal((await plan()).plan,'full_year');pass('Renaming and replacing the head coach preserve the paid team and revoke departed access');
 await as(ids.parent);assert.equal((await plan()).full_access,true);assert.equal((await plan()).can_manage_plan,false);assert.equal((await plan()).paid_through,null);
 await as(ids.athlete);assert.equal((await plan()).full_access,true);await assert.rejects(()=>resource('equipment_add',{title:'No staff access',quantity:1}),/staff required/);pass('Linked parents and athletes share team coverage without gaining billing or staff permissions');
 await db.exec('reset role');await db.query('delete from public.athlete_guardians where guardian_user_id=$1',[ids.parent]);await as(ids.parent);await assert.rejects(()=>plan(),/access required/);
 await db.exec('reset role');await db.query('update public.roster_memberships set active=false where athlete_id=$1',[ids.a]);await as(ids.athlete);await assert.rejects(()=>plan(),/access required/);pass('Removed guardian links and inactive athlete rosters cannot read team plan details');
 await as(ids.shared);await assert.rejects(()=>plan(),/Personal account/);
 await as(ids.mate);await assert.rejects(()=>plan(ids.other),/access required/);pass('Managed accounts and unrelated teams cannot obtain plan details');
 await apply({event:'cancel',revision:1,status:'canceled'});await as(ids.outsider);assert.equal((await plan()).full_access,true);assert.equal((await plan()).subscription_status,'canceled');
 await apply({event:'revoke',revision:2,status:'revoked'});await as(ids.outsider);assert.equal((await plan()).full_access,false);pass('Cancellation keeps prepaid access through term end; revocation removes paid access immediately');
 await apply({event:'past-due',revision:3,status:'past_due'});await as(ids.outsider);assert.equal((await plan()).full_access,false);
 await apply({event:'expired',revision:4,start:'2024-01-01T00:00:00Z',end:'2025-01-01T00:00:00Z'});await as(ids.outsider);assert.equal((await plan()).subscription_status,'expired');assert.equal((await resource('equipment_list')).rows.length,1);
 await apply({event:'future',revision:5,start:'2098-01-01T00:00:00Z',end:'2099-01-01T00:00:00Z'});await as(ids.outsider);assert.equal((await plan()).full_access,false);pass('Past due, expired and future terms cannot silently unlock paid tools or delete records');
 await apply({event:'renewal',revision:6});await as(ids.outsider);assert.equal((await plan()).full_access,true);const item=(await resource('equipment_list')).rows[0];
 await resource('equipment_out',{id:item.id,revision:0});await assert.rejects(()=>resource('equipment_out',{id:item.id,revision:0}),/Inventory changed/);
 await resource('equipment_in',{id:item.id,revision:1});assert.equal((await resource('equipment_list')).rows[0].checked_out,0);pass('Renewal restores inventory edits and existing inventory conflict checks still apply');
 await db.exec('reset role');const manager=randomUUID();await db.query("insert into public.team_memberships(team_id,user_id,role,permissions) values($1,$2,'manager','{\"equipment\":true}')",[ids.team,manager]);
 await as(manager);assert.equal((await resource('equipment_list')).write,true);assert.equal((await plan()).can_manage_plan,false);
 await db.exec('reset role');await db.query("update public.teams set organization_id=$1 where id=$2",[ids.other,ids.team]);await db.query("insert into public.organization_memberships values($1,$2,'organization_admin')",[ids.other,ids.coach]);await as(ids.coach);assert.equal((await plan()).can_manage_plan,true);pass('Equipment managers retain only their assigned role; organization administrators can view team billing status');
 for(const role of ['service_role','authenticated','anon']){
  await db.exec('reset role;set role '+role);
  for(const name of ['team_subscriptions','team_subscription_events','team_plan_settings'])await assert.rejects(()=>db.query('select * from private.'+name),/permission denied/);
  await assert.rejects(()=>db.query("update private.team_plan_settings set pilot_enabled=true"),/permission denied/);
  await assert.rejects(()=>db.query("select private.apply_team_subscription_event('manual','fake',$1,'fake',0,'active',now(),now()+interval '1 year')",[ids.other]),/permission denied/);
  await assert.rejects(()=>db.query("select private.team_feature_allowed($1,'equipment_management')",[ids.team]),/permission denied/);
 }
 await assert.rejects(()=>plan(),/permission denied/);pass('Clients cannot read billing identifiers, change plans or pilot mode, grant access, or call internal feature helpers');
 await as(ids.coach);const projected=JSON.stringify(await plan());assert(!projected.includes('verified-subscription'));assert(!projected.includes('purchase-1'));pass('Plan projection omits provider and payment references');
 await pilot(false);await apply({event:'expire-again',revision:7,status:'expired'});await as(ids.coach);
 await assert.rejects(()=>db.query("select private.wm_resources('equipment_add',$1)",[JSON.stringify({team:ids.team,title:'Direct bypass',quantity:1})]),/Full Year/);
 const media=await resource('media_list');assert.equal(media.write,true);assert.deepEqual(media.rows,[]);pass('Direct resource helper calls cannot bypass paid inventory checks; existing file access remains unchanged');
 await db.exec('reset role');await assert.rejects(()=>db.query("select private.team_feature_allowed($1,'misspelled_feature')",[ids.team]),/Unknown team feature/);
 await assert.rejects(()=>apply({event:'bad-period',revision:8,start:f.dates.end,end:f.dates.start}),/Invalid/);pass('Unknown feature keys and invalid billing periods fail closed');
 fs.writeFileSync(path.join(root,'validation/team-plan-db.json'),JSON.stringify({passed:tests.length,tests,engine:'Isolated PGlite; actual migration and captured resource functions; synthetic records only',limits:'Independent concurrent database sessions and payment-provider verification not tested'},null,2));await db.close();
})().catch(e=>{console.error(e);process.exit(1)});
