-- Uses only synthetic accounts, teams and athlete records. Every row rolls back.
begin;
do $$
declare org uuid=gen_random_uuid();t uuid=gen_random_uuid();ss uuid=gen_random_uuid();ev uuid=gen_random_uuid();
 coach uuid=gen_random_uuid();parent uuid=gen_random_uuid();athlete uuid=gen_random_uuid();mate uuid=gen_random_uuid();outsider uuid=gen_random_uuid();
 a uuid=gen_random_uuid();b uuid=gen_random_uuid();bout uuid=gen_random_uuid();otherbout uuid=gen_random_uuid();
 p jsonb;q jsonb;payload jsonb;denied boolean;
begin
 insert into auth.users(id,raw_user_meta_data) values(coach,'{"name":"Tournament validation coach"}'),(parent,'{"name":"Tournament validation parent"}'),(athlete,'{"name":"Tournament validation athlete"}'),(mate,'{"name":"Tournament validation teammate"}'),(outsider,'{"name":"Tournament validation outsider"}');
 insert into public.organizations(id,name) values(org,'Temporary tournament validation');
 insert into public.teams(id,organization_id,name) values(t,org,'Temporary tournament validation team');
 insert into public.seasons(id,team_id,name,active) values(ss,t,'Temporary season',true);
 insert into public.athletes(id,organization_id,first_name,last_name) values(a,org,'Example','Athlete'),(b,org,'Example','Athlete');
 insert into public.roster_memberships(season_id,athlete_id) values(ss,a),(ss,b);
 insert into public.team_memberships(team_id,user_id,athlete_id,role) values(t,coach,null,'head_coach'),(t,parent,a,'parent_guardian'),(t,athlete,a,'athlete'),(t,mate,b,'athlete');
 insert into public.athlete_guardians(athlete_id,guardian_user_id,name) values(a,parent,'Example Guardian');
 insert into public.team_events(id,team_id,season_id,event_type,title,starts_at,created_by) values(ev,t,ss,'tournament','Synthetic Invitational',now(),coach);
 perform set_config('request.jwt.claim.sub',coach::text,true);execute 'set local role authenticated';
 p:=public.tournament_request('setup',jsonb_build_object('team_id',t,'event_id',ev,'timezone','America/Denver'));
 if p->>'workspace_id' is null or p->>'provider_connected'<>'false' then raise exception 'Workspace setup incorrect';end if;
 payload:=jsonb_build_object('team_id',t,'event_id',ev,'id',bout,'athlete_id',a,'division','16U','weight_class','120 lb','bout_number','101','mat','1','opponent','Private Opponent','status','queued','estimated_start',now()+interval '30 minutes','revision',0,'queue_order',1,'bracket_url','https://example.test/bracket');
 p:=public.tournament_request('save_bout',payload);
 p:=public.tournament_request('save_bout',payload||jsonb_build_object('id',otherbout,'athlete_id',b,'division','Junior','mat','2'));
 if jsonb_array_length(p->'bouts')<>2 then raise exception 'Duplicate bout numbers or names merged';end if;
 denied:=false;begin perform public.tournament_request('save_bout',payload);exception when others then if sqlerrm not like '%Bout changed%' then raise;end if;denied:=true;end;
 if not denied then raise exception 'Duplicate retry overwrote bout';end if;
 perform set_config('request.jwt.claim.sub',athlete::text,true);
 p:=public.tournament_request('board',jsonb_build_object('team_id',t,'event_id',ev));
 if jsonb_array_length(p->'bouts')<>1 or (p->'bouts')::text like '%Private Opponent%' or p->'bouts'->0 ? 'bracket_url' then raise exception 'Restricted projection leaked data';end if;
 denied:=false;begin perform public.tournament_request('visibility',jsonb_build_object('team_id',t,'athlete_id',a,'level','full','revision',0));exception when others then if sqlerrm not like '%parent%' then raise;end if;denied:=true;end;
 if not denied then raise exception 'Athlete changed visibility';end if;
 perform set_config('request.jwt.claim.sub',parent::text,true);
 p:=public.tournament_request('board',jsonb_build_object('team_id',t,'event_id',ev));
 if jsonb_array_length(p->'bouts')<>1 or p->'bouts'->0->>'opponent'<>'Private Opponent' then raise exception 'Parent scope incorrect';end if;
 p:=public.tournament_request('visibility',jsonb_build_object('team_id',t,'athlete_id',a,'level','mat_only','revision',0));
 denied:=false;begin perform public.tournament_request('visibility',jsonb_build_object('team_id',t,'athlete_id',b,'level','full','revision',0));exception when others then if sqlerrm not like '%parent%' then raise;end if;denied:=true;end;
 if not denied then raise exception 'Parent changed unrelated child';end if;
 perform set_config('request.jwt.claim.sub',athlete::text,true);
 p:=public.tournament_request('board',jsonb_build_object('team_id',t,'event_id',ev));q:=p->'bouts'->0;
 if q ?| array['opponent','estimated_start','division','weight_class','status','result','bracket_url'] or q->>'mat'<>'1' then raise exception 'Mat-only projection incorrect';end if;
 denied:=false;begin perform 1 from private.tournament_bouts;exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Raw table is readable';end if;
 denied:=false;begin perform private.tournament_athlete_access(t,a);exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'Helper is executable';end if;
 perform set_config('request.jwt.claim.sub',outsider::text,true);
 denied:=false;begin perform public.tournament_request('board',jsonb_build_object('team_id',t,'event_id',ev));exception when others then if sqlerrm not like '%access required%' then raise;end if;denied:=true;end;
 if not denied then raise exception 'Outsider read tournament';end if;
 execute 'reset role';update public.team_memberships set active=false where user_id=parent;
 perform set_config('request.jwt.claim.sub',parent::text,true);execute 'set local role authenticated';
 denied:=false;begin perform public.tournament_request('board',jsonb_build_object('team_id',t,'event_id',ev));exception when others then if sqlerrm not like '%access required%' then raise;end if;denied:=true;end;
 if not denied then raise exception 'Removed parent still has access';end if;
 execute 'reset role';perform set_config('tournaments042.validation','workspace,duplicate-bout-identity,retry-conflict,athlete-restriction,parent-authority,parent-scope,unrelated-child-denial,mat-only-projection,raw-table-denial,helper-denial,outsider-denial,parent-revocation',true);
end $$;
select current_setting('tournaments042.validation') as passed, 'Synthetic records rolled back; no invitations or notifications sent' as cleanup;
rollback;
