const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),{chromium}=require('playwright'),{PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite'),{fixture,root}=require('./tournaments-fixture.cjs');
(async()=>{
 const db=new PGlite(),f=await fixture(db),{ids}=f;await f.call('setup',{timezone:'America/Denver'});const first=f.row();await f.call('save_bout',first);await f.call('save_bout',f.row({athlete_id:ids.b,division:'Junior',mat:'2',estimated_start:null,status:'on_deck'}));
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']}),ctx=await browser.newContext({viewport:{width:390,height:844},hasTouch:true}),p=await ctx.newPage(),errors=[],tests=[];p.on('pageerror',e=>errors.push(e.message));const pass=s=>{tests.push(s);console.log('PASS',s)};
 let serial=Promise.resolve(),delay=0;await p.exposeFunction('tournamentBackend',(q,uid)=>{const work=serial.then(async()=>{await f.as(uid);try{const data=await f.call(q.p_action,q.p_data);if(delay)await new Promise(r=>setTimeout(r,delay));return {data,error:null};}catch(e){return {error:{message:e.message}}}});serial=work.catch(()=>{});return work;});
 let init=fs.readFileSync(path.join(root,'tests/browser-fixture.js'),'utf8').replace('    F.calls.push',"    if(name==='tournament_request')return window.tournamentBackend(args,F.session.user.id);\n    F.calls.push");
 await ctx.addInitScript({content:init});await p.route('**/*',r=>r.request().url()==='https://wm.test/'?r.fulfill({contentType:'text/html',body:fs.readFileSync(path.join(root,'index.html'),'utf8')}):r.request().url().includes('supabase-js')?r.fulfill({contentType:'text/javascript',body:''}):r.abort());await p.goto('https://wm.test/');
 async function as(uid,staff){await p.evaluate(({ids,uid,staff})=>{closeSheets();session=fixture.session={user:{id:uid}};activeTeam={id:ids.team,name:'Synthetic team'};activeSeason={id:ids.season};managedLogin=null;isStaff=actualIsStaff=isTeamAdmin=actualIsTeamAdmin=staff;isManager=false;viewMode=staff?'staff':'parent';accountProfileData={id:uid,ui_preferences:{}};show('authView',false);show('appView',true);applyRoleUI();}, {ids,uid,staff});}
 await as(ids.coach,true);await p.evaluate(id=>WMTournaments.open(id),ids.event);assert.equal(await p.locator('[data-tournament-bout]').count(),2);assert.match(await p.locator('#tournamentBody').innerText(),/Private Opponent/);assert.match(await p.locator('#tournamentBody').innerText(),/Time unknown/);pass('Coach board loads actual SQL projections, multiple mats and unknown timing');
 await p.locator('[data-tournament-edit="'+first.id+'"]').click();await p.locator('[name="mat"]').fill('4');await p.locator('[name="status"]').selectOption('in_hole');await p.locator('#tournamentBoutForm button[type="submit"]').click();await p.waitForFunction(()=>document.getElementById('tournamentStatus').textContent.startsWith('Saved'));assert.match(await p.locator('[data-tournament-bout="'+first.id+'"]').innerText(),/Mat 4/);pass('Editing a manual assignment saves through SQL and refreshes the board');
 await p.locator('#tournamentAdd').click();await p.locator('[name="division"]').fill('Open');await p.locator('[name="weight_class"]').fill('57 kg');await p.locator('[name="bout_number"]').fill('101');await p.locator('[name="queue_order"]').fill('9');await p.locator('#tournamentBoutForm button[type="submit"]').click();await p.waitForFunction(()=>document.querySelectorAll('[data-tournament-bout]').length===3);pass('Coach adds a second division without treating the displayed bout number as an identity');
 assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.locator('#tournamentSheet').evaluate(n=>n.scrollTop=0);await p.screenshot({path:path.join(root,'validation/tournament-coach-phone.png')});
 await as(ids.parent,false);await p.evaluate(id=>WMTournaments.open(id),ids.event);assert.equal(await p.locator('#tournamentAdd').count(),0);assert(await p.locator('.tournament-family').count());await p.locator('.tournament-family summary').click();await p.locator('[data-tournament-visibility]').selectOption('mat_only');await p.locator('[data-tournament-save-visibility]').click();await p.waitForFunction(()=>document.getElementById('tournamentStatus').textContent===''&&document.querySelectorAll('[data-tournament-bout]').length===2);assert.match(await p.locator('#tournamentBody').innerText(),/Private Opponent/);pass('Parent can save the athlete restriction while retaining their own full child view');
 await as(ids.athlete,false);await p.evaluate(id=>WMTournaments.open(id),ids.event);assert.equal(await p.locator('[data-tournament-bout]').count(),1);const text=await p.locator('#tournamentCards').innerText();assert(!/Private Opponent|120 lb|16U|in the hole|Time unknown|minutes/i.test(text));assert.equal(await p.locator('#tournamentCards a').count(),0);assert.equal(await p.locator('[data-tournament-visibility]').count(),0);await p.screenshot({path:path.join(root,'validation/tournament-athlete-mat-only-phone.png')});pass('Restricted athlete sees only their mat/bout assignment with no bracket shortcut or parent controls');
 await p.locator('#tournamentDemo').click();assert.match(await p.locator('#tournamentBody').innerText(),/Sample Wrestler A/);assert(!/Private Opponent/.test(await p.locator('#tournamentBody').innerText()));let n=await p.locator('#tournamentAlertLog .notice').count();await p.locator('[data-sim="advance"]').click();assert((await p.locator('#tournamentAlertLog .notice').count())>n);await p.locator('[data-sim="mat"]').click();assert.match(await p.locator('#tournamentAlertLog').innerText(),/assignment changed/);await p.locator('#tournamentDemoView').selectOption('mat_only');assert(!/Opponent|minutes|deck/.test(await p.locator('#tournamentCards').innerText()));assert.equal(await p.locator('#tournamentAlertLog .notice').count(),0);pass('Demo uses only synthetic wrestlers and simulates timing, mat updates and viewer restrictions');
 await p.locator('#tournamentDemoView').selectOption('full');await p.locator('[data-sim="stale"]').click();assert.match(await p.locator('#tournamentCards').innerText(),/May be out of date/);await p.locator('[data-sim="unknown"]').click();assert.match(await p.locator('#tournamentCards').innerText(),/Time unknown/);await p.setViewportSize({width:1280,height:900});await p.screenshot({path:path.join(root,'validation/tournament-demo-desktop.png')});pass('Stale and unknown estimates are visible and desktop layout remains usable');
 await as(ids.coach,true);await p.evaluate(id=>WMTournaments.open(id),ids.event);delay=150;await p.evaluate(async()=>{const promise=WMTournaments.refresh(true);session=fixture.session={user:{id:'different-account'}};WMTournaments.sync();await promise;});assert(await p.locator('#tournamentSheet').isHidden());assert.equal(await p.locator('#tournamentBody').innerText(),'');delay=0;pass('Account changes clear the sheet and discard in-flight responses');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(root,'validation/tournaments-042-browser.json'),JSON.stringify({passed:tests.length,tests,engine:'Chromium whole page + actual SQL in isolated PGlite; synthetic accounts only'},null,2));await browser.close();await db.close();
})().catch(e=>{console.error(e);process.exit(1)});
