const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite'),{fixture,root}=require('./tournaments-fixture.cjs');
(async()=>{
 const db=new PGlite(),f=await fixture(db),{ids,as,call,row}=f,tests=[];const pass=s=>{tests.push(s);console.log('PASS',s)};
 let c=await call('context');assert(c.can_manage);assert.equal(c.events.length,1);let b=await call('setup',{timezone:'America/Denver'});assert(b.workspace_id);pass('Coach opens a manual workspace only on the active team tournament');
 const first=row(),second=row({athlete_id:ids.b,division:'Junior',mat:'2'}),later=row({division:'Open',queue_order:2,opponent:'Later Private Opponent'});for(const r of [first,second,later])b=await call('save_bout',r);assert.equal(b.bouts.length,3);assert.equal(new Set(b.bouts.map(x=>x.id)).size,3);assert.equal(b.bouts.filter(x=>x.bout_number==='101').length,3);pass('Duplicate names and displayed bout numbers retain separate athlete, division and bout identities');
 await assert.rejects(()=>call('save_bout',first),/Bout changed/);await assert.rejects(()=>call('save_bout',{...first,revision:1,bracket_url:'javascript:alert(1)'}));b=await call('board');assert.equal(b.bouts.find(x=>x.id===first.id).revision,1);pass('Lost-response retries and invalid bracket URLs do not overwrite saved bouts');
 await as(ids.athlete);b=await call('board');assert.equal(b.bouts.length,1);assert.equal(b.bouts[0].id,first.id);assert.equal(b.bouts[0].opponent,undefined);assert.equal(b.bouts[0].bracket_url,undefined);assert(!JSON.stringify(b).includes('Private Opponent'));await assert.rejects(()=>call('save_bout',row()),/Coach|coach/);await assert.rejects(()=>call('visibility',{athlete_id:ids.a,level:'full',revision:0}),/parent/);pass('Athlete defaults to their next bout with opponent, bracket and future-bout data excluded by SQL');
 await as(ids.parent);b=await call('board');assert.equal(b.bouts.length,2);assert.equal(b.bouts[0].opponent,'Private Opponent');await assert.rejects(()=>call('visibility',{athlete_id:ids.b,level:'full',revision:0}),/parent/);await call('visibility',{athlete_id:ids.a,level:'mat_only',revision:0});await assert.rejects(()=>call('visibility',{athlete_id:ids.a,level:'full',revision:0}),/changed/);pass('Linked parent keeps full child information, changes only their child and detects stale settings');
 await as(ids.athlete);b=await call('board');assert.equal(b.bouts.length,1);for(const key of ['opponent','bracket_url','result','estimated_start','status','division','weight_class','revision'])assert.equal(b.bouts[0][key],undefined);pass('Mat-only API response excludes timing, status, opponent, division, weight and results');
 await as(ids.coach);b=await call('board');assert.equal(b.bouts.length,3);assert.equal(b.bouts[0].opponent,'Private Opponent');await call('save_bout',{...first,revision:1,status:'complete',result:'Coach correction: fall'});await as(ids.athlete);b=await call('board');assert.equal(b.bouts[0].id,later.id);pass('Coach access remains full; completing one bout advances the athlete to their next assignment');
 await as(ids.parent);await call('visibility',{athlete_id:ids.a,level:'full',revision:1});await as(ids.athlete);b=await call('board');assert.equal(b.bouts.length,2);assert(b.bouts.some(x=>x.result==='Coach correction: fall'));pass('Parent-approved full view includes coach-sourced results and bracket references');
 for(const u of [ids.outsider,ids.shared]){await as(u);await assert.rejects(()=>call('board'),/access required|Personal account/);}await as(ids.coach);await assert.rejects(()=>call('board',{event_id:ids.otherEvent}),/active team/);pass('Unrelated accounts, managed logins and other-team event IDs are denied');
 await assert.rejects(()=>db.query('select * from private.tournament_bouts'),/permission denied/);await assert.rejects(()=>db.query('select private.tournament_athlete_access($1,$2)',[ids.team,ids.a]),/permission denied/);await db.exec('reset role;set role anon');await assert.rejects(()=>call('context'),/permission denied/);pass('Anonymous callers and direct raw table or helper reads are denied');
 await db.exec('reset role');await db.query('update public.team_memberships set active=false where user_id=$1',[ids.parent]);await as(ids.parent);await assert.rejects(()=>call('board'),/access required/);await db.exec('reset role');await db.query('update public.roster_memberships set active=false where athlete_id=$1',[ids.a]);await as(ids.athlete);await assert.rejects(()=>call('board'),/access required/);pass('Guardian removal and roster removal revoke subsequent reads');
 fs.writeFileSync(path.join(root,'validation/tournaments-042-db.json'),JSON.stringify({passed:tests.length,tests,engine:'PGlite, synthetic users and tables; actual migration functions'},null,2));await db.close();
})().catch(e=>{console.error(e);process.exit(1)});
