const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{step}=require('../src/tournament-alerts.js');
const now=Date.parse('2026-09-25T18:00:00Z'),iso=n=>new Date(n).toISOString();let state={},tests=[];const pass=s=>{tests.push(s);console.log('PASS',s)};
const row={id:'a',bout_number:'101',mat:'1',status:'queued',visibility:'upcoming',revision:1,updated_at:iso(now),estimated_start:iso(now+65*60000)};
function advance(minutes,change={}){const t=now+minutes*60000;Object.assign(row,change,{updated_at:iso(t)});const r=step(state,[row],t);state=r.state;return r.alerts;}
assert.equal(advance(0).length,0);const seen=[];for(const min of [5,35,50,55,60])seen.push(...advance(min).map(x=>x.kind));assert.deepEqual(seen,['minutes:60','minutes:30','minutes:15','minutes:10','minutes:5']);assert.equal(advance(60).length,0);state=JSON.parse(JSON.stringify(state));assert.equal(advance(60).length,0);pass('60/30/15/10/5 thresholds emit once and remain deduplicated across repeated reads or restored state');
let r=advance(60,{revision:2,estimated_start:iso(now+80*60000),mat:'3'});assert(r.some(x=>x.kind.startsWith('reschedule')));assert(r.some(x=>x.kind.startsWith('mat')));assert.equal(advance(65).length,0);pass('Delayed estimates and mat changes produce updates without repeating earlier countdowns');
for(const [i,status] of ['in_hole','on_deck','up_next','on_mat'].entries()){r=advance(65,{status,revision:3+i});assert(r.some(x=>x.kind==='status:'+status));assert.equal(advance(65).length,0);}pass('Readiness statuses emit once each');
assert.equal(step(state,[{...row,revision:1,mat:'9',updated_at:iso(now)}],now+65*60000).alerts.length,0);pass('Delayed older revisions cannot generate alerts or replace a newer assignment');
for(const bad of [{estimated_start:null},{estimated_start:iso(now-60000)},{stale:true},{updated_at:iso(now-660000)}])assert.equal(step({},[{...row,status:'queued',updated_at:iso(now),estimated_start:iso(now+60000),...bad}],now).alerts.length,0);pass('Unknown, expired or stale timing never generates a countdown');
r=step({},[{...row,status:'queued',updated_at:iso(now),estimated_start:iso(now+7*60000)}],now).alerts;assert.deepEqual(r.map(x=>x.kind),['minutes:10']);pass('Joining late emits only the closest useful threshold instead of a burst of missed alerts');
r=step({},[{...row,visibility:'mat_only',updated_at:iso(now)}],now);assert.equal(r.alerts.length,0);r=step(r.state,[{...row,visibility:'mat_only',mat:'2',revision:9,updated_at:iso(now+1000)}],now+1000);assert.equal(r.alerts.length,1);assert(!/Opponent|minutes|deck|bracket/i.test(r.alerts[0].body));pass('Mat-only simulation includes only assignment updates');
fs.writeFileSync(path.resolve(__dirname,'../validation/tournament-alerts-042.json'),JSON.stringify({passed:tests.length,tests,scope:'Pure simulation; no background delivery or live provider'},null,2));
