const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite'),{fixture,root}=require('./voting-fixture.cjs');
async function main(){const db=new PGlite();const {ids,sessions,as,req,policy,meeting,round,detail,open,close}=await fixture(db);const results=[],pass=n=>{results.push(n);console.log('PASS',n)};
await as(ids.admin,null);await assert.rejects(req({action:'ballot_context'}),/personal/);await as(ids.admin,sessions[ids.a]);await assert.rejects(req({action:'ballot_context'}),/personal/);await as(null);await assert.rejects(req({action:'ballot_inbox'}),/personal/);await as(ids.shared);await assert.rejects(req({action:'ballot_context'}),/personal/);pass('Missing, mismatched, anonymous and shared-login sessions denied');
await db.exec('reset role');await db.query('update auth.sessions set not_after=now()-interval \'1 minute\' where id=$1',[sessions[ids.a]]);await as(ids.a);await assert.rejects(req({action:'ballot_inbox'}),/personal/);await db.exec('reset role');await db.query('update auth.sessions set not_after=null where id=$1',[sessions[ids.a]]);await db.query('update auth.users set banned_until=now()+interval \'1 day\' where id=$1',[ids.a]);await as(ids.a);await assert.rejects(req({action:'ballot_inbox'}),/personal/);await db.exec('reset role');await db.query('update auth.users set banned_until=null where id=$1',[ids.a]);pass('Expired and banned sessions cannot vote or inspect ballots');
let m=await meeting(false),r=await round(m);await assert.rejects(open(r.id),/awaiting release/);await db.exec('reset role');await db.exec("create or replace function private.vote039_released() returns boolean language sql stable set search_path='' as $$select true$$;");pass('Official voting is release-gated until verified');
await as(ids.member);await assert.rejects(detail(r.id),/access/);await assert.rejects(req({action:'ballot_open',id:r.id,revision:1,confirm_rules:true,confirm_delegates:true}),/chair/);pass('Title-only president and ordinary member cannot control or inspect a draft');
await as(ids.outsider);await assert.rejects(req({action:'ballot_detail',id:r.id}),/access/);await assert.rejects(req({action:'ballot_detail',id:r.id,organization_id:ids.other}),/access/);pass('Tenant and record-ID substitution attacks denied');
await as(ids.admin);const context=await req({action:'ballot_context'});assert(!context.directory.some(p=>[ids.minor,ids.shared,ids.outsider].includes(p.id)));pass('Delegate choices exclude minors, team logins and unrelated tenants');
let bad=await round(m,{policy:{}});await assert.rejects(open(bad.id),/governing rule/);bad=await round(m,{policy:{...policy,tie:''}});await assert.rejects(open(bad.id),/Explicitly/);bad=await round(m,{policy:{...policy,min_attendance:4}});await assert.rejects(open(bad.id),/quorum/);bad=await round(m,{policy:{...policy,basis:'electorate',abstentions:'exclude'}});await assert.rejects(open(bad.id),/includes abstentions/);pass('Rules, electronic authorization, tie treatment and reachable quorum must be explicit');
await as(ids.admin);await assert.rejects(round(m,{participants:[{entity_id:ids.club1,delegate_user_id:ids.a},{entity_id:ids.club2,delegate_user_id:ids.a}]}),/unique/);await assert.rejects(round(m,{participants:[{entity_id:ids.club1,delegate_user_id:ids.minor}]}),/adult/);await assert.rejects(round(m,{participants:[{entity_id:ids.a,delegate_user_id:ids.a}]}),/eligible entries/);pass('One account per seat; ineligible delegates and wrong electorates rejected');
await db.exec('reset role');await db.query("update private.organization_affiliates set membership_review='unreviewed',voting_review='unreviewed',voting_eligible=false where id=$1",[ids.club1]);await assert.rejects(open(r.id),/Affiliate directory/);await db.exec('reset role');await db.query("update private.organization_affiliates set membership_review='confirmed',voting_review='eligible',voting_eligible=true where id=$1",[ids.club1]);pass('Historical directory alone does not authorize a live club ballot');
await open(r.id);await as(ids.a);let state=await detail(r.id);assert.equal(state.result,null);assert(!('participants' in state));assert.equal(state.my_ballot.can_vote,true);assert(!(JSON.stringify(state).includes('EXECUTIVE')));const receipt=await req({action:'ballot_cast',id:r.id,choice:'for'});assert.deepEqual(receipt,{recorded:true,already_recorded:false});assert.deepEqual(await req({action:'ballot_cast',id:r.id,choice:'against'}),{recorded:true,already_recorded:true});pass('Atomic acceptance gives a choice-free receipt; retry or changed choice cannot add a vote');
await as(ids.admin);state=await detail(r.id);assert.equal(state.result,null);assert.equal(state.participants.filter(p=>p.submitted).length,1);assert(!JSON.stringify(state).includes('yes_count'));await assert.rejects(req({action:'ballot_test_cast',id:r.id,entity_id:ids.club2,choice:'for'}),/Test simulation/);await assert.rejects(req({action:'ballot_save',id:r.id,revision:state.revision,meeting_id:m.id,motion:'Change',electorate:'affiliates',participants:[],policy}),/immutable/);await assert.rejects(req({action:'meeting_adjourn',id:m.id,revision:m.revision}),/Close or cancel/);pass('Chair sees participation only; opened rules freeze; official simulation and premature adjournment blocked');
await req({action:'ballot_substitute',id:r.id,revision:state.revision,entity_id:ids.club1,delegate_user_id:ids.d,confirm_delegates:true});await as(ids.a);await assert.rejects(req({action:'ballot_cast',id:r.id,choice:'for'}),/designated/);await as(ids.d);assert.equal((await req({action:'ballot_cast',id:r.id,choice:'against'})).already_recorded,true);pass('Replacing a delegate after submission preserves the spent ballot');
await as(ids.admin);state=await detail(r.id);await assert.rejects(req({action:'ballot_substitute',id:r.id,revision:state.revision,entity_id:ids.club2,delegate_user_id:ids.a,confirm_delegates:true}),/another seat/);pass('An earlier delegate cannot move to another club to cast twice');
await db.exec('reset role');await db.query("update private.organization_affiliates set status='archived',name='Changed later' where id=$1",[ids.club2]);await as(ids.b);await req({action:'ballot_cast',id:r.id,choice:'against'});await as(ids.c);await req({action:'ballot_cast',id:r.id,choice:'abstain'});state=await close(r.id);assert.deepEqual(state.result.totals,{for:1,against:1,abstain:1});assert.equal(state.result.outcome,'not_passed');assert.equal(state.result.approval_denominator,2);assert.equal(state.participants.find(p=>p.entity_id===ids.club2).name,'club2');pass('Frozen electorate survives affiliation changes; results appear only on close and apply the explicit tie policy');
await as(ids.member);assert.deepEqual((await detail(r.id)).result.totals,{for:1,against:1,abstain:1});assert(!('participants' in (await detail(r.id))));await as(ids.d);assert((await req({action:'ballot_cast',id:r.id,choice:'for'})).already_recorded);pass('Closed aggregate visible to authorized members; post-close retry stays choice-free');
await db.exec('reset role');await db.query("update private.organization_affiliates set status='active' where id=$1",[ids.club2]);
for(const [name,patch,votes,expected,den] of [
 ['zero ballots',{},[],'no_decision',0],['insufficient turnout',{min_ballots:3},['for'],'no_quorum',1],['abstentions only',{},['abstain','abstain'],'no_decision',0],
 ['two thirds',{numerator:2,denominator:3,comparison:'gte'},['for','for','against'],'passed',3],['abstentions included',{abstentions:'include'},['for','abstain','abstain'],'not_passed',3],
 ['entire electorate',{basis:'electorate',abstentions:'include'},['for'],'not_passed',3],['tie new round',{tie:'new_round'},['for','against'],'new_round_required',2]]){
 const b=await round(m,{policy:{...policy,...patch}});await open(b.id);for(let i=0;i<votes.length;i++){await as(ids[['a','b','c'][i]]);await req({action:'ballot_cast',id:b.id,choice:votes[i]});}const out=(await close(b.id)).result;assert.equal(out.outcome,expected);assert.equal(out.approval_denominator,den);pass('Outcome policy: '+name);
}
await as(ids.admin);const replayQ={action:'ballot_save',meeting_id:m.id,motion:'Amended wording',prior_id:r.id,change_reason:'Amend recorded motion',electorate:'board',participants:[{entity_id:ids.a}],policy,request_id:require('crypto').randomUUID()};const second=await req(replayQ);assert.deepEqual(await req(replayQ),second);assert.equal((await detail(second.id)).round_number,2);await assert.rejects(req({...replayQ,motion:'Different'}),/different content/);assert.equal((await detail(r.id)).result.totals.for,1);pass('Amendments create a new immutable round; administrative retries are idempotent');
await open(second.id);await as(ids.a);await req({action:'ballot_cast',id:second.id,choice:'for'});await close(second.id);pass('Board ballots use individual eligible seats independently of club ballots');
let test=await meeting(true);assert.equal((await req({action:'meeting_list'})).meetings.find(x=>x.id===test.id).is_test,true);assert.equal(test.document.roll.filter(x=>x.name.startsWith('Demo club')).length,3);const testRound=await round(test,{participants:[{entity_id:ids.club1},{entity_id:ids.club2}]});await open(testRound.id);await as(ids.admin);await req({action:'ballot_test_cast',id:testRound.id,entity_id:ids.club1,choice:'for'});await req({action:'ballot_test_cast',id:testRound.id,entity_id:ids.club2,choice:'against'});state=await close(testRound.id);assert.equal(state.result.is_test,true);await as(ids.member);await assert.rejects(detail(testRound.id),/access/);pass('Test-only unassigned seats can be simulated; test results stay out of member records');
await as(ids.admin);test=await req({action:'meeting_detail',id:test.id});await req({action:'meeting_adjourn',id:test.id,revision:test.revision});test=await req({action:'meeting_detail',id:test.id});assert.equal(test.is_test,true);assert.equal(test.private_ballot_results.length,1);await as(ids.member);await assert.rejects(req({action:'meeting_detail',id:test.id}),/access/);await as(ids.admin);await assert.rejects(req({action:'meeting_delete_test',id:test.id,revision:test.revision,confirm_delete:'yes'}),/Type DELETE/);await assert.rejects(req({action:'meeting_delete_test',id:m.id,revision:m.revision,confirm_delete:'DELETE'}),/Only a test/);const delQ={action:'meeting_delete_test',id:test.id,revision:test.revision,confirm_delete:'DELETE',request_id:require('crypto').randomUUID()};await req(delQ);assert.equal((await req(delQ)).deleted,true);await assert.rejects(detail(testRound.id),/access/);pass('Test deletion requires confirmation, removes its votes/minutes, retries safely, and cannot delete official meetings');
await as(ids.admin);let live=await req({action:'meeting_detail',id:m.id});await req({action:'meeting_adjourn',id:m.id,revision:live.revision});live=await req({action:'meeting_detail',id:m.id});assert(live.private_ballot_results.length>=8);assert.equal(live.minutes_label,'UNAPPROVED MINUTES');assert(!JSON.stringify(live.private_ballot_results).includes('delegate'));pass('Adjourned minutes snapshot only closed aggregate ballot results');
for(const table of ['organization_secret_totals','organization_secret_participants','organization_secret_delegations','organization_secret_rounds','organization_secret_requests'])await assert.rejects(db.query('select * from private.'+table),/permission denied/);await assert.rejects(db.query('select private.vote039_released()'),/permission denied/);await assert.rejects(db.query("select private.meeting038_request('{}')"),/permission denied/);pass('Direct tables and helper/bypass APIs are inaccessible');
await db.exec('reset role');const cols=(await db.query("select column_name from information_schema.columns where table_schema='private' and table_name='organization_secret_totals' order by column_name")).rows.map(r=>r.column_name);assert.deepEqual(cols,['abstain_count','no_count','round_id','yes_count']);assert.equal((await db.query("select count(*)::int n from private.ops_audit where action in ('ballot_cast','ballot_test_cast')")).rows[0].n,0);pass('Stored aggregates have no voter, timestamp or receipt fields; no cast audit records');
fs.writeFileSync(path.join(root,'validation/voting-db.json'),JSON.stringify({engine:'PGlite / PostgreSQL',passed:results.length,tests:results},null,2));await db.close();}
main().catch(e=>{console.error({message:e.message,code:e.code,position:e.position,where:e.where,stack:e.stack?.split('\n').slice(0,3).join('\n')});process.exit(1)});
