const fs=require('fs'),path=require('path'),{randomUUID}=require('crypto');
const root=path.resolve(__dirname,'..');
const migration=n=>fs.readFileSync(path.join(root,'supabase/migrations',fs.readdirSync(path.join(root,'supabase/migrations')).find(x=>x.endsWith(n+'.sql'))),'utf8');
async function fixture(db){
 await db.exec(fs.readFileSync(path.join(__dirname,'structure-fixture.sql'),'utf8'));
 await db.exec("create table auth.users(id uuid primary key,banned_until timestamptz);create table auth.sessions(id uuid primary key,user_id uuid,not_after timestamptz);create function auth.jwt() returns jsonb language sql stable as $$select nullif(current_setting('request.jwt.claims',true),'')::jsonb$$;create table public.athlete_private_identity(athlete_id uuid primary key,birth_date date);");
 await db.exec(migration('organization_structure_02036'));await db.exec('drop table private.organization_meetings;');await db.exec(fs.readFileSync(path.join(__dirname,'meetings-existing-schema.sql'),'utf8'));await db.exec(migration('organization_meetings_02038'));await db.exec(migration('organization_private_ballots_02039'));await db.exec(migration('private_ballot_meeting_list_fix_02039'));
 await db.exec("create or replace function public.organization_governance(p_request jsonb) returns jsonb language sql set search_path='' as $$select private.organization_governance(p_request)$$;");
 const ids=Object.fromEntries(['admin','secretary','chair','a','b','c','d','member','outsider','minor','shared','org','other','team','athlete','club1','club2','club3'].map(k=>[k,randomUUID()])),sessions={};
 for(const k of ['admin','secretary','chair','a','b','c','d','member','outsider','minor','shared']){await db.query('insert into public.profiles values($1,$2)',[ids[k],k]);await db.query('insert into auth.users(id) values($1)',[ids[k]]);sessions[ids[k]]=randomUUID();await db.query('insert into auth.sessions(id,user_id) values($1,$2)',[sessions[ids[k]],ids[k]]);}
 await db.query("insert into public.organizations(id,name) values($1,'Voting fixture'),($2,'Other tenant')",[ids.org,ids.other]);
 for(const k of ['admin','secretary','chair','a','b','c','d','member','minor','shared'])await db.query('insert into public.organization_memberships values($1,$2,$3)',[ids.org,ids[k],k==='admin'?'organization_admin':'assistant_coach']);
 await db.query("insert into public.organization_memberships values($1,$2,'organization_admin')",[ids.other,ids.outsider]);
 await db.query("insert into public.teams values($1,$2,'Test team')",[ids.team,ids.org]);await db.query("insert into public.athletes values($1,current_date-interval '15 years')",[ids.athlete]);await db.query("insert into public.team_memberships(team_id,user_id,role,athlete_id) values($1,$2,'athlete',$3)",[ids.team,ids.minor,ids.athlete]);await db.query('insert into private.team_logins values($1)',[ids.shared]);
 for(const k of ['a','b','c'])await db.query('insert into private.organization_positions(organization_id,title,assigned_user_id,voting_member) values($1,$2,$3,true)',[ids.org,'Board '+k,ids[k]]);
 await db.query("insert into private.organization_positions(organization_id,title,assigned_user_id) values($1,'President',$2)",[ids.org,ids.member]);
 for(const k of ['club1','club2','club3'])await db.query("insert into private.organization_affiliates(id,organization_id,name,membership_review,voting_review,voting_eligible,review_note) values($1,$2,$3,'confirmed','eligible',true,'Test fixture only')",[ids[k],ids.org,k]);
 const as=async(user,sessionId)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user||'']);await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:user,session_id:sessionId===undefined?sessions[user]:sessionId})]);await db.exec('set role authenticated');};
 const req=async q=>(await db.query('select public.organization_governance($1::jsonb) r',[JSON.stringify({organization_id:ids.org,request_id:randomUUID(),...q})])).rows[0].r;
 const policy={governing_rule:'Fixture rule: majority; attendance 1, ballots 1, abstain excluded; ties do not pass.',electronic_authorization:'Fixture authorization only',min_attendance:1,min_ballots:1,numerator:1,denominator:2,comparison:'gt',basis:'votes_cast',abstentions:'exclude',tie:'not_passed'};
 async function meeting(test=false){await as(ids.admin);let m=await req({action:'meeting_create',title:test?'Test meeting':'Official fixture',is_test:test,meeting_at:new Date().toISOString(),secretary_user_id:ids.secretary,chair_user_id:ids.chair,confirm_adult:true});let d=await req({action:'meeting_detail',id:m.id});d.document.roll.forEach(x=>x.present=true);await req({action:'meeting_save',id:m.id,revision:d.revision,document:d.document,confidential_notes:'EXECUTIVE FIXTURE ONLY'});d=await req({action:'meeting_detail',id:m.id});await req({action:'meeting_start',id:m.id,revision:d.revision});return (await req({action:'meeting_detail',id:m.id}));}
 async function round(m,options={}){await as(ids.admin);return req({action:'ballot_save',meeting_id:m.id,motion:'Fixture motion',electorate:'affiliates',participants:[{entity_id:ids.club1,delegate_user_id:ids.a},{entity_id:ids.club2,delegate_user_id:ids.b},{entity_id:ids.club3,delegate_user_id:ids.c}],policy,...options});}
 async function detail(id){return req({action:'ballot_detail',id});}
 async function open(id){await as(ids.admin);const r=await detail(id);return req({action:'ballot_open',id,revision:r.revision,confirm_rules:true,confirm_delegates:true});}
 async function close(id){await as(ids.admin);const r=await detail(id);await req({action:'ballot_close',id,revision:r.revision});return detail(id);}
 return {db,ids,sessions,as,req,policy,meeting,round,detail,open,close};
}
module.exports={fixture,migration,root};
