import test from 'node:test';
import assert from 'node:assert/strict';
import {createAppleNotificationHandler} from './apple-notification-handler.mjs';
const id='10000000-0000-4000-8000-000000000001';
const request=(body={signedPayload:'header.payload.signature'},headers={})=>new Request('https://example.test/notifications',{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
function fixture(extra={}){const calls=[];return {calls,handler:createAppleNotificationHandler({enabled:true,allowRequest:async()=>true,apple:{notificationTransaction:async payload=>{calls.push('verify');return {notificationID:id,evidence:{canonical:true}};}},persistVerified:async value=>{calls.push('persist');return {notificationID:value.notificationID,status:'stored'};},...extra})};}
test('signed verification precedes persistence; success only after commit acknowledgement',async()=>{const {handler,calls}=fixture();const r=await handler(request());assert.equal(r.status,200);assert.deepEqual(calls,['verify','persist']);assert.deepEqual(await r.json(),{accepted:true});assert.match(r.headers.get('cache-control'),/no-store/);});
test('duplicate durable notification is acknowledged',async()=>{const {handler}=fixture({persistVerified:async()=>({notificationID:id,status:'duplicate'})});assert.equal((await handler(request())).status,200);});
test('failed verification never persists and diagnostics stay private',async()=>{let writes=0;const {handler}=fixture({apple:{notificationTransaction:async()=>{throw Error('PRIVATE SIGNED PAYLOAD');}},persistVerified:async()=>{writes++;}});const r=await handler(request());assert.equal(r.status,503);assert.equal(writes,0);assert.doesNotMatch(await r.text(),/PRIVATE/);});
test('write failure, wrong ID or unconfirmed persistence never acknowledges Apple',async()=>{for(const persistVerified of [async()=>{throw Error('SQL SECRET');},async()=>({notificationID:id,status:'queued'}),async()=>({notificationID:'wrong',status:'stored'})]){const {handler}=fixture({persistVerified});const r=await handler(request());assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/SECRET/);}});
test('body fields, encoding and size are bounded before verification',async()=>{const {handler,calls}=fixture();for(const body of [{signedPayload:'bad'},{signedPayload:'header.payload.signature',userID:'forged'},[],{signedPayload:'a'.repeat(200000)}])assert.equal((await handler(request(body))).status,400);assert.equal((await handler(request(undefined,{'Content-Type':'text/plain'}))).status,400);assert.deepEqual(calls,[]);});
test('disabled, browser and throttled requests do not verify or persist',async()=>{const disabled=fixture({enabled:false});assert.equal((await disabled.handler(request())).status,503);assert.deepEqual(disabled.calls,[]);const browser=fixture();assert.equal((await browser.handler(request(undefined,{Origin:'https://theteammanager.app'}))).status,403);assert.deepEqual(browser.calls,[]);const limited=fixture({allowRequest:async()=>false});assert.equal((await limited.handler(request())).status,429);assert.deepEqual(limited.calls,[]);});
test('acknowledgement waits for durable storage to finish',async()=>{let release;const gate=new Promise(r=>release=r);let completed=false;const {handler}=fixture({persistVerified:async()=>{await gate;return {notificationID:id,status:'stored'};}});const pending=handler(request()).then(r=>{completed=true;return r;});await new Promise(r=>setImmediate(r));assert.equal(completed,false);release();assert.equal((await pending).status,200);});
test('verified TEST succeeds without any subscription inbox write',async()=>{let writes=0;const {handler}=fixture({apple:{notificationTransaction:async()=>({notificationID:id,kind:'test'})},persistVerified:async()=>{writes++;}});assert.equal((await handler(request())).status,200);assert.equal(writes,0);});
