import test from 'node:test';import assert from 'node:assert/strict';import {createBillingHandler} from './billing-handler.mjs';
const request=(body={action:'prepare',data:{productID:'synthetic',target:{kind:'family'}}},extra={})=>new Request('https://backend.invalid/billing',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer synthetic',...extra.headers},body:JSON.stringify(body),...Object.fromEntries(Object.entries(extra).filter(([k])=>k!=='headers'))});
function fixture(extra={}){const calls=[],context={};const auth={authenticate:async token=>{calls.push(['auth',token]);return context;}};const intents={prepare:async(ctx,data)=>{assert.equal(ctx,context);calls.push(['prepare',data]);return {appAccountToken:'synthetic'};},abandon:async(ctx,data)=>{assert.equal(ctx,context);calls.push(['abandon',data]);return {cancelled:true};}};const delivery={deliver:async(ctx,data)=>{assert.equal(ctx,context);calls.push(['deliver',data]);return {transactionID:'1001',originalTransactionID:'1001'};}};return {calls,handler:createBillingHandler({enabled:true,auth,intents,delivery,...extra})};}
test('route defaults to disabled before credentials or storage are configured',async()=>{const response=await createBillingHandler({})(request());assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:'billing_unavailable'});});
test('prepare, delivery and abandon receive only server-minted context',async()=>{for(const action of ['prepare','deliver','abandon']){const {handler,calls}=fixture();const response=await handler(request({action,data:{synthetic:true}}));assert.equal(response.status,200);assert.equal(calls[0][0],'auth');assert.equal(calls[1][0],action);assert.equal(response.headers.get('Cache-Control'),'no-store');}});
test('foreign origins cannot reach authentication or receipt processing',async()=>{const {handler,calls}=fixture();const response=await handler(request(undefined,{headers:{Origin:'https://evil.invalid'}}));assert.equal(response.status,403);assert.equal(calls.length,0);assert.equal(response.headers.get('Access-Control-Allow-Origin'),null);});
test('allowed browser origin has explicit preflight; native requests need no origin',async()=>{const {handler}=fixture();const preflight=await handler(new Request('https://backend.invalid/billing',{method:'OPTIONS',headers:{Origin:'https://theteammanager.app'}}));assert.equal(preflight.status,204);assert.equal(preflight.headers.get('Access-Control-Allow-Origin'),'https://theteammanager.app');assert.equal(preflight.headers.get('Access-Control-Allow-Credentials'),null);assert.equal((await handler(request())).status,200);});
test('extra actor, paid or unknown commands are rejected before authentication',async()=>{for(const body of [{action:'prepare',data:{},actor:'evil'},{action:'grant',data:{}},{action:'deliver',data:[]},{action:'deliver',data:'signed'}]){const {handler,calls}=fixture();assert.equal((await handler(request(body))).status,400);assert.equal(calls.length,0);}});
test('oversized bodies and wrong media type fail before receipt parsing',async()=>{const {handler,calls}=fixture();assert.equal((await handler(request({action:'deliver',data:{signedTransaction:'x'.repeat(65536)}}))).status,413);assert.equal((await handler(request(undefined,{headers:{'Content-Type':'text/plain'}}))).status,400);assert.equal(calls.length,0);});
test('ended sessions return sign-in-required without processing purchases',async()=>{const {handler,calls}=fixture({auth:{authenticate:async()=>{throw Error('unauthorized');}}});const response=await handler(request());assert.equal(response.status,401);assert.equal(calls.length,0);});
test('database or Apple errors do not leak keys or raw receipts',async()=>{const {handler}=fixture({delivery:{deliver:async()=>{throw Error('private signing key and signed receipt');}}});const response=await handler(request({action:'deliver',data:{signedTransaction:'synthetic'}}));assert.equal(response.status,503);assert.deepEqual(await response.json(),{error:'purchase_delivery_unconfirmed'});});

test('access and coverage routes receive verified contexts and sanitize selection errors',async()=>{
 const context={};const calls=[];
 const handler=createBillingHandler({enabled:true,auth:{authenticate:async()=>context},
  access:{read:async(ctx,data)=>{assert.equal(ctx,context);calls.push(data);return {teamPro:false,familyVideo:false};}},
  coverage:{select:async(ctx,data)=>{assert.equal(ctx,context);if(data.athleteIDs?.length)throw Object.assign(Error('family_coverage_forbidden'),{code:'P0001'});return {selectedCount:0};}}});
 assert.equal((await handler(request({action:'access',data:{teamID:'synthetic'}}))).status,200);
 assert.deepEqual(calls,[{teamID:'synthetic'}]);
 assert.deepEqual(await (await handler(request({action:'coverage',data:{athleteIDs:[]}}))).json(),{selectedCount:0});
 const denied=await handler(request({action:'coverage',data:{athleteIDs:['synthetic']}}));
 assert.equal(denied.status,403);assert.deepEqual(await denied.json(),{error:'family_coverage_not_authorized'});
});
