import test from 'node:test';
import assert from 'node:assert/strict';
import {PurchaseIntentService} from './purchase-intent.mjs';
const userID='11111111-1111-4111-8111-111111111111',teamID='22222222-2222-4222-8222-222222222222',otherID='33333333-3333-4333-8333-333333333333',token='44444444-4444-4444-8444-444444444444';
const actor=()=>({userID,liveSession:true,confirmed:true});
const team=()=>({productID:'com.damonmele.wrestlingmanager.teampro.annual',target:{kind:'team',teamID}});
const family=()=>({productID:'com.damonmele.wrestlingmanager.familyvideo.monthly',target:{kind:'family'}});
function fixture(){const state={actor:actor(),current:actor(),allowTeam:true,allowFamily:true,binding:null,saved:[]};const service=new PurchaseIntentService({auth:{currentActor:async()=>state.actor},repository:{intentTransaction:async(_,fn)=>fn({currentActor:async()=>state.current,canPurchaseTeam:async()=>state.allowTeam,canPurchaseFamily:async()=>state.allowFamily,getTeamPurchaseBinding:async()=>state.binding,saveIntent:async x=>state.saved.push(x)})},token:()=>token,clock:()=>1800000000000});return {state,service};}
test('authorized team purchase receives an opaque server token',async()=>{const {state,service}=fixture();assert.deepEqual(await service.prepare({},team()),{appAccountToken:token});assert.equal(state.saved[0].teamID,teamID);});
test('family intent resolves ownership from the authenticated account',async()=>{const {state,service}=fixture();await service.prepare({},family());assert.equal(state.saved[0].familyOwnerID,userID);assert.equal(state.saved[0].teamID,null);});
test('client cannot supply owner, paid flag, token or mismatched scope',async()=>{for(const alter of [x=>x.userID=otherID,x=>x.paid=true,x=>x.token=token,x=>x.target={kind:'family'},x=>x.productID='toString',x=>x.target.familyOwnerID=otherID]){const {state,service}=fixture(),r=team();alter(r);await assert.rejects(service.prepare({},r));assert.equal(state.saved.length,0);}});
test('family request cannot choose a team or another owner',async()=>{for(const patch of [{teamID},{familyOwnerID:otherID}]){const {service}=fixture(),r=family();Object.assign(r.target,patch);await assert.rejects(service.prepare({},r));}});
test('current team authority and family eligibility are required',async()=>{for(const [flag,request] of [['allowTeam',team()],['allowFamily',family()]]){const {state,service}=fixture();state[flag]=false;await assert.rejects(service.prepare({},request));assert.equal(state.saved.length,0);}});
test('one purchaser cannot redirect existing Team Pro binding to another team',async()=>{const {state,service}=fixture();state.binding={teamID:otherID};await assert.rejects(service.prepare({},team()),/team_already_bound/);assert.equal(state.saved.length,0);state.binding={teamID};await service.prepare({},team());assert.equal(state.saved.length,1);});
test('account changes and session revocation inside lock prevent all intent writes',async()=>{for(const patch of [{userID:otherID},{liveSession:false},{deleted:true},{managedTeamLogin:true},{deletionFrozen:true}]){const {state,service}=fixture();Object.assign(state.current,patch);await assert.rejects(service.prepare({},team()));assert.equal(state.saved.length,0);}});
test('commit failure never returns a purchase token',async()=>{const {service}=fixture();service.repository.intentTransaction=async(_,fn)=>{await fn({currentActor:async()=>actor(),canPurchaseTeam:async()=>true,getTeamPurchaseBinding:async()=>null,saveIntent:async()=>{}});throw Error('commit_failed');};await assert.rejects(service.prepare({},team()),/commit_failed/);});
test('abandon cancels only an owned unbound intent and releases its pending selection',async()=>{const {state,service}=fixture();let cancelled=false,released=false;service.repository.abandonTransaction=async(_,fn)=>fn({currentActor:async()=>state.current,getIntent:async()=>({userID,token,teamID}),cancelIntent:async()=>{cancelled=true;},releaseUnusedTeamBinding:async()=>{released=true;}});assert.deepEqual(await service.abandon({}, {appAccountToken:token}),{cancelled:true});assert.equal(cancelled,true);assert.equal(released,true);});
test('abandon cannot erase paid or another account intent',async()=>{for(const intent of [{userID:otherID,token,teamID},{userID,token,teamID,boundOriginalTransactionID:'1001'}]){const {state,service}=fixture();service.repository.abandonTransaction=async(_,fn)=>fn({currentActor:async()=>state.current,getIntent:async()=>intent,cancelIntent:async()=>{throw Error('must_not_run');}});await assert.rejects(service.abandon({}, {appAccountToken:token}),/intent_not_owned|purchase_already_bound/);}});
