/* Team goals 0.20.40: accomplishments and explicit parent-approved profile sharing. */
window.WMGoals=(()=>{
 let inline=false;
 const $g=id=>document.getElementById(inline?({teamGoalsSheet:'lockerGoalsPane',teamGoalsBody:'lockerGoalsBody',teamGoalsTitle:'lockerGoalsTitle',teamGoalsStatus:'lockerGoalsStatus'}[id]||id):id),E=esc;
 let epoch=0,owner=null,originTeam=null,context=null,current=null,busy=false,draft=null,dirty=false;
 const allowed=()=>!!session?.user?.id&&!managedLogin&&!document.body.classList.contains('kiosk-locked')&&!document.querySelector('#appLockOverlay:not(.hidden)');
 const valid=t=>t===epoch&&allowed()&&owner===session?.user?.id&&originTeam===(activeTeam?.id||null)&&!$g('teamGoalsSheet').classList.contains('hidden');
 const note=s=>{$g('teamGoalsStatus').textContent=s||'';};
 const button=(s,attr='')=>`<button type="button" class="secondary" ${attr}>${E(s)}</button>`;
 const preset=()=>[{id:'academic',label:'Academic',count:5,prompt:''},{id:'wrestling',label:'Wrestling',count:5,prompt:''}];
 const call=async(action,data)=>{if(!allowed()||owner!==session?.user?.id||originTeam!==(activeTeam?.id||null))throw Error('Account or team changed. Reopen team goals.');const {data:out,error}=await client.rpc('team_goals_request',{p_action:action,p_data:data});if(error)throw Error(error.message);return out;};
 function reset(){epoch++;busy=false;owner=null;context=null;current=null;draft=null;dirty=false;for(const id of ['teamGoalsBody','lockerGoalsBody'])document.getElementById(id)?.replaceChildren();show('teamGoalsSheet',false);inline=false;}
 function start(inLocker=false){if(!allowed())return false;closeSheets();inline=inLocker;document.getElementById(inline?'teamGoalsBody':'lockerGoalsBody')?.replaceChildren();owner=session.user.id;originTeam=activeTeam?.id||null;if(!inline)openSheet('teamGoalsSheet');note('Loading team goals…');return true;}
 function freeze(form){const els=[...form.querySelectorAll('input,textarea,button')].map(e=>[e,e.disabled]);els.forEach(([e])=>e.disabled=true);return ()=>els.forEach(([e,disabled])=>{if(e.isConnected)e.disabled=disabled;});}
 function run(fn){return async e=>{try{await fn(e);}catch(err){note(err.message);}};}
 async function open(athlete=null,inLocker=false){if(!start(inLocker))return;if(!activeTeam){note('Choose a team first.');return;}await load(activeTeam.id,athlete);}
 async function load(team,athlete=null){const t=++epoch;note('Loading team goals…');try{const c=await call('context',{team_id:team});if(!valid(t))return;context=c;current=null;draft=null;note('');if(athlete&&c.enabled)return await view(athlete);home();}catch(e){if(valid(t)){note(e.message);$g('teamGoalsBody').innerHTML=button('Retry','id="goalsRetry"');$g('goalsRetry').onclick=()=>load(team,athlete);}}}
 function home(){$g('teamGoalsSheet').scrollTop=0;current=null;draft=null;$g('teamGoalsTitle').textContent='Team Goals';$g('teamGoalsBody').innerHTML=`<h3>${E(context.team_name)}</h3>${context.can_configure?button('Coach goal settings','id="goalsSettings"'):''}${context.enabled?`<p>${context.categories.map(c=>`${c.count} ${E(c.label.toLowerCase())}`).join(' + ')} goals per athlete</p><p class="goal-instructions">${E(context.instructions)}</p><p class="fine">Athletes and their linked parents can edit their own goals. Teammates, coaches and team leaders can view them.</p><div class="wp-grid">${context.athletes.map(a=>button(a.name,`data-goal-athlete="${E(a.id)}"`)).join('')||'<p>No active athletes available.</p>'}</div>`:'<p>Team goals are off. A coach can enable them for this team.</p><p>Saved goals are kept when this is switched off.</p>'}`;
 $g('goalsSettings')?.addEventListener('click',settings);$g('teamGoalsBody').querySelectorAll('[data-goal-athlete]').forEach(b=>b.onclick=()=>view(b.dataset.goalAthlete));}
 function settings(){if(busy)return;note('');draft=structuredClone(context);$g('teamGoalsSheet').scrollTop=0;renderSettings();}
 function collectSettings(){draft.enabled=$g('goalsEnabled').checked;draft.instructions=$g('goalsInstructions').value;draft.categories=[...$g('goalCategories').querySelectorAll('[data-category]')].map(row=>({id:row.dataset.category,label:row.querySelector('[data-label]').value,count:Number(row.querySelector('[data-count]').value),prompt:row.querySelector('[data-prompt]').value}));}
 function renderSettings(){
 $g('teamGoalsTitle').textContent='Coach Goal Settings';$g('teamGoalsBody').innerHTML=`${button('Back to team goals','id="goalsBack"')}<h3>${E(context.team_name)}</h3><form id="goalsSettingsForm"><label class="toggle-row"><span><b>Enable team goals</b><small>Show goals to athletes, their linked parents and teammates.</small></span><input id="goalsEnabled" type="checkbox" ${draft.enabled?'checked':''}></label><label>Instructions for athletes<textarea id="goalsInstructions" maxlength="1200" rows="3" placeholder="What should your athletes work toward?">${E(draft.instructions)}</textarea></label><h3>Goal categories</h3><p class="fine">Choose 1–6 categories with 1–10 goals each. Removed categories and extra slots stay in saved goals. Increasing a category’s count restores its extra slots.</p><div id="goalCategories">${draft.categories.map((c,i)=>`<fieldset data-category="${E(c.id)}"><legend>Category ${i+1}</legend><label>Name<input data-label value="${E(c.label)}" maxlength="50" required></label><label>Number of goals<input data-count type="number" min="1" max="10" step="1" required value="${c.count}"></label><label>Writing prompt (optional)<input data-prompt maxlength="240" value="${E(c.prompt)}" placeholder="Describe a clear, achievable goal"></label>${button('Remove category',`data-remove="${i}" ${draft.categories.length===1?'disabled':''}`)}</fieldset>`).join('')}</div><div class="wp-actions">${button('Add category',`id="goalsAddCategory" ${draft.categories.length>=6?'disabled':''}`)}${button('Use 5 academic + 5 wrestling','id="goalsPreset"')}</div><button id="goalsSettingsSave" class="wide">Save team goal settings</button></form>`;
 $g('goalsBack').onclick=()=>{if(busy)return;note('');home();};
 $g('goalsAddCategory').onclick=()=>{collectSettings();draft.categories.push({id:'category_'+crypto.randomUUID().replaceAll('-',''),label:'',count:5,prompt:''});renderSettings();};
 $g('goalsPreset').onclick=()=>{collectSettings();draft.categories=preset();renderSettings();};
 $g('goalCategories').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{collectSettings();draft.categories.splice(Number(b.dataset.remove),1);renderSettings();});
 $g('goalsSettingsForm').onsubmit=run(async ev=>{ev.preventDefault();if(busy)return;collectSettings();const t=epoch;busy=true;const thaw=freeze($g('goalsSettingsForm'));try{const c=await call('settings_save',{team_id:context.team_id,enabled:draft.enabled,instructions:draft.instructions,categories:draft.categories,revision:context.revision});if(!valid(t))return;context=c;home();note('Team goal settings saved.');}catch(e){if(valid(t))note(e.message+' Your changes are still here.');}finally{if(valid(t)){busy=false;thaw();}}});
 }
 async function view(athlete){if(busy)return;const t=++epoch;note('Loading athlete goals…');try{const out=await call('view',{team_id:context.team_id,athlete_id:athlete});if(!valid(t))return;current=out;renderGoals();note('');}catch(e){if(valid(t))note(e.message);}}
 function renderGoals(){
 dirty=false; $g('teamGoalsSheet').scrollTop=0;const p=current,keys=p.categories.flatMap(c=>Array.from({length:c.count},(_,i)=>c.id+':'+(i+1))),filled=keys.filter(k=>p.entries[k]?.text?.trim()).length,completed=keys.filter(k=>p.entries[k]?.complete&&p.entries[k]?.text?.trim()).length;
 $g('teamGoalsTitle').textContent=p.name+' · Goals';$g('teamGoalsBody').innerHTML=`<div class="wp-actions">${button('Team goals','id="goalsBack"')}${button('Reload saved goals','id="goalsReload"')}</div><p>${E(p.team_name)}</p><p class="goal-instructions">${E(p.instructions)}</p><p class="goal-progress">${filled} of ${keys.length} written · ${completed} completed in current goals · <span class="goal-star" aria-hidden="true">★</span> ${(p.accomplishments||[]).length} accomplishments</p><div id="goalCelebration" role="status" aria-live="polite"></div><p class="fine">Visible to this athlete, linked parents, active teammates, coaches and team leaders. ${p.editable?'You can save a draft and come back to finish.':'View only · the athlete and their linked parents fill these in.'}</p><form id="athleteGoalsForm">${p.categories.map(c=>`<section class="goal-category"><h3>${E(c.label)} Goals · ${c.count}</h3>${c.prompt?`<p class="goal-instructions">${E(c.prompt)}</p>`:''}${Array.from({length:c.count},(_,i)=>{const k=c.id+':'+(i+1),v=p.entries[k]||{text:'',complete:false};return `<div class="goal-card" data-goal-key="${E(k)}"><label><b>${E(c.label)} goal ${i+1}</b>${p.editable?`<textarea data-goal-text ${v.complete?'readonly':''} maxlength="600" rows="3" placeholder="Write your goal…">${E(v.text)}</textarea>`:`<p class="goal-text">${E(v.text||'Not written yet')}</p>`}</label>${p.editable?`<label class="toggle-row"><span>${v.complete?'<span class="goal-star" aria-hidden="true">★</span> Goal accomplished!':'Mark goal accomplished'}</span><input data-goal-complete type="checkbox" ${v.complete?'checked':''}></label>`:`<p class="goal-state">${v.complete?'<span class="goal-star" aria-hidden="true">★</span> Goal accomplished!':v.text?'In progress':'Not started'}</p>`}${v.complete&&p.editable?button('Set a new goal',`data-goal-replace="${E(k)}"`):''}</div>`;}).join('')}</section>`).join('')}${p.editable?'<button id="athleteGoalsSave" class="wide">Save my goals</button>':''}</form><p class="fine">Adjust an active goal whenever it is too easy or too hard. Checking completion saves your goals. To correct a completed goal, uncheck completion first.</p>${history(p)}${sharing(p)}${Object.keys(p.archived||{}).length?`<details class="wp-panel"><summary>Saved goals outside the current team template</summary><p class="fine">Kept for you and your linked parents. Extra slots return when the coach raises that category’s count.</p>${Object.values(p.archived).map(v=>`<h4>${E(v.label)} goal ${Number(v.slot)}</h4><p>${E(v.text)}</p>`).join('')}</details>`:''}`;
 $g('goalsBack').onclick=()=>{if(busy)return;note('');home();};$g('goalsReload').onclick=()=>view(p.athlete_id);
 const form=$g('athleteGoalsForm');form.oninput=()=>{dirty=true;note('Unsaved goal changes.');};
 form.onsubmit=run(async ev=>{ev.preventDefault();await persist('save');});
 form.querySelectorAll('[data-goal-complete]').forEach(box=>box.onchange=()=>{box.closest('[data-goal-key]').querySelector('[data-goal-text]').readOnly=box.checked;form.requestSubmit();});
 form.querySelectorAll('[data-goal-replace]').forEach(b=>b.onclick=()=>persist('replace',b.dataset.goalReplace));
 $g('goalSharingForm')?.addEventListener('submit',run(async ev=>{ev.preventDefault();if(busy)return;if(dirty){note('Save your goal edits before changing profile sharing.');return;}const t=epoch;busy=true;const thaw=freeze(ev.currentTarget);try{const out=await call('profile_sharing',{team_id:p.team_id,athlete_id:p.athlete_id,enabled:$g('goalProfileShare').checked,revision:p.profile_sharing.revision});if(!valid(t))return;current=out;renderGoals();note('Profile goal sharing saved.');}catch(e){if(valid(t))note('Profile sharing was not confirmed. '+e.message);}finally{if(valid(t)){busy=false;thaw();}}}));
 async function persist(action,key=null){if(busy||!p.editable)return;const entries={};form.querySelectorAll('[data-goal-key]').forEach(row=>{entries[row.dataset.goalKey]={text:row.querySelector('[data-goal-text]').value.trim(),complete:row.querySelector('[data-goal-complete]').checked};});if(Object.values(entries).some(v=>v.complete&&!v.text)){note('Write a goal before marking it accomplished.');return;}const t=epoch;busy=true;const thaw=freeze(form);note('Saving goals…');try{const out=await call(action,{team_id:p.team_id,athlete_id:p.athlete_id,settings_revision:p.settings_revision,revision:p.revision,entries,goal_key:key});if(!valid(t))return;const newStars=(out.accomplishments||[]).filter(a=>!(p.accomplishments||[]).some(old=>old.id===a.id));current=out;renderGoals();note(action==='replace'?'Accomplishment saved. Write your next goal in the empty space.':'Goals saved.');if(newStars.length){$g('goalCelebration').innerHTML='<div class="goal-celebration"><span aria-hidden="true"><span class="goal-star" aria-hidden="true">★</span></span><div><b>Goal accomplished!</b><p>'+E(newStars.length===1?newStars[0].text:newStars.length+' goals accomplished!')+'</p></div></div>';}
 if(action==='replace'){$g('athleteGoalsForm').querySelector('[data-goal-key="'+CSS.escape(key)+'"] [data-goal-text]')?.focus();}
 }catch(e){if(valid(t))note('Not saved or not yet confirmed. '+e.message+' Your writing is still here. Use Reload saved goals to check what reached the server.');}finally{if(valid(t)){busy=false;thaw();}}}

 }
 function history(p){return `<section class="goal-history"><h3><span class="goal-star" aria-hidden="true">★</span> Accomplished goals</h3><p class="fine">Finished goals stay here when you set a new goal. Unchecking a completion corrects it and removes that star.</p>${(p.accomplishments||[]).map(a=>`<article class="goal-card"><b><span class="goal-star" aria-hidden="true">★</span> ${E(a.category)} goal accomplished</b><p class="goal-text">${E(a.text)}</p><small>${a.completed_at?E(new Date(a.completed_at).toLocaleDateString()):'Completed earlier · date not recorded'}</small></article>`).join('')||'<p>No accomplished goals yet. Your first star starts with one goal.</p>'}</section>`;}
 function sharing(p){if(!p.profile_sharing?.can_change)return '';return `<section class="goal-profile-sharing"><h3>Parent profile sharing</h3><form id="goalSharingForm"><label class="toggle-row"><span>Show these goals on my athlete’s profile</span><input id="goalProfileShare" type="checkbox" ${p.profile_sharing.enabled?'checked':''}></label><p class="fine">Shares this team’s current goal text and completion marks with signed-in members who can view the athlete’s shared profile. Future edits appear there too. The profile must also be shared. Accomplishment history and archived goals stay in the team/family view.</p><button>Save profile sharing</button></form></section>`;}
 function sharedProfile(rows=[]){return rows.length?`<section class="wp-panel"><h3>🎯 Goals</h3><p class="fine">Shared with parent/guardian approval.</p>${rows.map(t=>`<h4>${E(t.team)}</h4>${t.goals.map(g=>`<article class="goal-card"><b>${E(g.category)}${g.complete?' · <span class="goal-star" aria-hidden="true">★</span> Goal accomplished!':''}</b><p class="goal-text">${E(g.text)}</p></article>`).join('')}`).join('')}</section>`:'';}
 async function profile(id){if(!start())return;const t=++epoch;try{const rows=await call('profile',{profile_id:id});if(!valid(t))return;if(rows.length===1)return load(rows[0].team_id,rows[0].athlete_id);note('');$g('teamGoalsTitle').textContent='Profile Goals';$g('teamGoalsBody').innerHTML=rows.length?'<p>Choose a team.</p>'+rows.map((r,i)=>button(r.team_name,`data-goal-team="${i}"`)).join(''):'<p>No enabled team goals are available to you for this profile.</p>';$g('teamGoalsBody').querySelectorAll('[data-goal-team]').forEach(b=>b.onclick=()=>{const r=rows[Number(b.dataset.goalTeam)];return load(r.team_id,r.athlete_id);});}catch(e){if(valid(t))note(e.message);}}
 document.addEventListener('click',ev=>{if(!owner||!dirty)return;const target=ev.target.closest('[data-locker-section],[data-tab],[data-go],[data-close-sheet],#goalsBack,#goalsReload,#goalsSettings');if(!target)return;if(!confirm('Discard your unsaved goal edits?')){ev.preventDefault();ev.stopImmediatePropagation();}else dirty=false;},true);
 window.addEventListener('beforeunload',ev=>{if(dirty){ev.preventDefault();ev.returnValue='';}});
 $g('teamGoalsBtn').onclick=()=>open();$g('viewAthleteGoalsBtn').onclick=()=>open(viewAthleteId);$g('profileAthleteGoalsBtn').onclick=()=>open(profileAthleteId);
 return {open,profile,reset,sharedProfile,locker(){return open(null,true);},leaveLocker(){if(inline)reset();},sync(){if(owner&&(!allowed()||owner!==session?.user?.id||originTeam!==(activeTeam?.id||null)))reset();if(!owner&&allowed()&&activeTeam&&!document.getElementById('lockerGoalsPane')?.classList.contains('hidden')&&!document.getElementById('homeTab')?.classList.contains('hidden'))open(null,true);}};
})();
