/* Past and upcoming events are edited in place, retaining their attendance and RSVP records. */
window.WMEventEdit=(()=>{
 'use strict';const $=id=>document.getElementById(id),E=esc;let generation=0,record=null,owner='',team='',busy=false;
 const sheet=document.createElement('section');sheet.id='eventEditSheet';sheet.className='sheet hidden';sheet.setAttribute('role','dialog');sheet.setAttribute('aria-label','Edit event');sheet.innerHTML='<div class="sheet-head"><h2>Edit event</h2><button type="button" id="eventEditClose" class="icon-close" aria-label="Close edit event">×</button></div><p id="eventEditStatus" role="status"></p><div id="eventEditBody"></div>';document.body.append(sheet);$('eventEditClose').onclick=()=>closeSheets();
 const btn=document.createElement('button');btn.id='editEventBtn';btn.className='secondary';btn.textContent='Edit event';$('deleteEventBtn').before(btn);btn.onclick=()=>open();
 const valid=g=>g===generation&&owner===session?.user?.id&&team===activeTeam?.id&&isStaff&&!managedLogin&&!document.body.classList.contains('kiosk-locked')&&$('appLockOverlay').classList.contains('hidden');
 function reset(){generation++;record=null;busy=false;owner=team='';$('eventEditBody').replaceChildren();sheet.classList.add('hidden');}
 function open(){reset();if(!isStaff||managedLogin||!activeEvent||activeEvent.team_id!==activeTeam?.id)return;record={...activeEvent};owner=session.user.id;team=activeTeam.id;const e=record;const input=(k,label,type='text')=>`<label>${E(label)}<input id="ee_${k}" type="${type}" value="${E(type==='datetime-local'?(e[k]?localDateTimeValue(new Date(e[k])):''):e[k]||'')}"></label>`;
 $('eventEditStatus').textContent='Change this event only. Attendance, RSVPs and checkout records stay attached.';$('eventEditBody').innerHTML=`<form id="eventEditForm">${input('title','Title')}${input('location_name','Location')}${input('location_address','Address')}<div class="two-col">${input('starts_at','Start','datetime-local')}${input('ends_at','End','datetime-local')}</div><div class="two-col">${input('arrival_at','Arrival','datetime-local')}${input('weigh_in_at','Weigh-in','datetime-local')}</div><label>Additional information<textarea id="ee_description" maxlength="10000">${E(e.description||'')}</textarea></label>${[['rsvp_enabled','RSVP enabled'],['attendance_required','Track attendance'],['counts_toward_season_attendance','Count toward season attendance'],['checkout_enabled','Ride-home checkout']].map(([k,label])=>`<label class="toggle-row"><span>${label}</span><input id="ee_${k}" type="checkbox" ${e[k]?'checked':''}></label>`).join('')}<button class="wide" type="submit">Save event changes</button></form>`;$('ee_title').required=$('ee_starts_at').required=true;$('ee_title').maxLength=200;$('eventEditForm').onsubmit=save;openSheet(sheet.id);window.WMScheduleTools?.mountEditor(e);}
 async function save(ev){ev.preventDefault();if(busy)return;const g=generation;if(!valid(g))return;const values={};for(const k of ['title','description','location_name','location_address'])values[k]=$('ee_'+k).value.trim();for(const k of ['starts_at','ends_at','arrival_at','weigh_in_at'])values[k]=toIsoOrNull($('ee_'+k).value);for(const k of ['rsvp_enabled','attendance_required','counts_toward_season_attendance','checkout_enabled'])values[k]=$('ee_'+k).checked;
 if(values.ends_at&&values.ends_at<=values.starts_at){$('eventEditStatus').textContent='End must be after the start.';return;}busy=true;const b=ev.currentTarget.querySelector('button[type=submit]');b.disabled=true;try{const repeating=window.WMScheduleTools?.handles();const r=repeating?{data:await WMScheduleTools.save(record,values)}:await client.rpc('edit_team_event',{p_id:record.id,p_expected:record.updated_at,p_values:values});if(repeating&&!r.data)return;if(!valid(g))return;if(r.error)throw Error(r.error.message);const id=record.id;activeEvent=r.data;closeSheets();await loadSchedule();if(!valid(g))return;await openEventDetail(id);message('Event updated. Saved attendance and RSVPs are still attached.');}catch(e){if(valid(g))$('eventEditStatus').textContent=e.message;}finally{if(valid(g)){busy=false;b.disabled=false;}}}
 return {open,reset};
})();
