/* Explicit repeat dates, local-clock scheduling and retry-safe series creation. */
window.WMEventRepeat=(()=>{
 'use strict';const $=id=>document.getElementById(id);let pending=null,busy=false,generation=0;
 const options=$('repeatPracticeOptions'),toggle=$('repeatPractice').closest('label'),box=document.createElement('section');box.id='eventRepeatBox';box.className='practice-repeat-box';$('practiceOptions').after(box);box.append(toggle,options);
 toggle.querySelector('b').textContent='Repeat event';toggle.querySelector('small').textContent='Create daily, weekly or monthly events through the date you choose.';
 const frequency=document.createElement('label');frequency.innerHTML='Repeat<select id="eventRepeatFrequency"><option value="weekly">Weekly · selected days</option><option value="daily">Daily</option><option value="monthly">Monthly · same date</option></select>';options.prepend(frequency);
 $('practiceWeekdays').previousElementSibling.textContent='Days each week';$('practiceRepeatStart').readOnly=true;
 const help=document.createElement('p');help.id='eventRepeatSummary';help.className='fine';help.setAttribute('aria-live','polite');options.append(help);
 const tz=document.createElement('p');tz.id='eventRepeatTimezone';tz.className='fine';options.append(tz);
 const keep=$('practiceKeepCompetitionDay').closest('label');
 function dates(start,last,mode,days){if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(last))return [];const a=new Date(start+'T12:00:00Z'),b=new Date(last+'T12:00:00Z');if(b<a||b-a>366*86400000)return [];const rows=[];for(let d=new Date(a);d<=b;d.setUTCDate(d.getUTCDate()+1)){if(mode==='weekly'&&!days.includes(d.getUTCDay()||7))continue;if(mode==='monthly'&&d.getUTCDate()!==a.getUTCDate())continue;rows.push(d.toISOString().slice(0,10));}return rows;}
 function refresh(){const on=$('repeatPractice').checked,mode=$('eventRepeatFrequency').value;options.classList.toggle('hidden',!on);$('practiceWeekdays').classList.toggle('hidden',mode!=='weekly');$('practiceWeekdays').previousElementSibling.classList.toggle('hidden',mode!=='weekly');keep.classList.toggle('hidden',selectedEventType!=='practice'||mode!=='weekly');const first=$('eventStart').value.slice(0,10);$('practiceRepeatStart').value=first;$('practiceRepeatEnd').min=first;
 const rows=dates(first,$('practiceRepeatEnd').value,mode,selectedPracticeWeekdays());help.textContent=rows.length?`${rows.length} event${rows.length===1?'':'s'} · ${rows[0]} through ${rows.at(-1)}. ${mode==='monthly'?'Months without this date are skipped. ':''}Each event can be opened and edited separately.`:'Choose an end date within one year'+(mode==='weekly'?' and at least one weekday.':'.');tz.textContent='Times stay the same in '+Intl.DateTimeFormat().resolvedOptions().timeZone+'.';}
 function freeze(on){$('eventSheet').querySelectorAll('input,select,textarea,.type-btn,[data-repeat-day]').forEach(e=>e.disabled=on);}
 function reset(){generation++;pending=null;busy=false;freeze(false);$('eventRepeatFrequency').value='weekly';$('saveEventBtn').disabled=false;$('saveEventBtn').textContent='Create Event';refresh();}
 function handles(){return $('repeatPractice').checked&&!(selectedEventType==='practice'&&$('eventRepeatFrequency').value==='weekly');}
 async function save(groups){if(busy)return;const g=generation,uid=session?.user?.id,team=activeTeam?.id,season=activeSeason?.id;const valid=()=>g===generation&&uid===session?.user?.id&&team===activeTeam?.id&&season===activeSeason?.id;try{
 if(!pending){const start=$('eventStart').value,end=$('eventEnd').value,frequency=$('eventRepeatFrequency').value,days=selectedPracticeWeekdays(),until=$('practiceRepeatEnd').value;
 if(!dates(start.slice(0,10),until,frequency,days).length)throw Error('Choose repeat dates within one year and at least one matching day.');if(end&&end<=start)throw Error('End must be after the start.');
 const day=start.slice(0,10),weighted=selectedEventType==='practice'&&$('practiceWeightTracking').checked;
 pending={client_id:crypto.randomUUID(),team_id:team,season_id:season,frequency,weekdays:days,until,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,start_local:start,end_local:end||null,arrival_local:$('eventArrival').value||null,weigh_in_local:$('eventWeighIn').value||null,pre_local:weighted?day+'T'+($('practicePreCutoff').value||start.slice(11,16)):null,post_local:weighted?day+'T'+($('practicePostStart').value||(end||start).slice(11,16)):null,event:{event_type:selectedEventType,title:$('eventTitle').value.trim(),description:$('eventDescription').value.trim(),location_name:$('eventLocation').value.trim(),location_address:$('eventAddress').value.trim(),practice_groups:groups,attendance_required:$('attendanceRequired').checked,rsvp_enabled:$('rsvpEnabled').checked,checkout_enabled:$('checkoutEnabled').checked,counts_toward_season_attendance:$('countsSeason').checked}};}
 busy=true;freeze(true);$('saveEventBtn').disabled=true;$('saveEventBtn').textContent='Creating events…';const r=await client.rpc('create_repeating_events',{p_data:pending});if(!valid())return;
 if(r.error){if(r.error.code==='P0001'||r.error.code?.startsWith('22')){pending=null;freeze(false);}throw Error(r.error.message);}
 pending=null;freeze(false);closeSheets();message(`${r.data.count} repeating events created.`);await loadSchedule();
 }catch(e){if(valid())message(e.message+(pending?' Retry to finish this same schedule without duplicates.':''),true);}finally{if(valid()){busy=false;$('saveEventBtn').disabled=false;$('saveEventBtn').textContent=pending?'Retry creating events':'Create Event';}}}
 $('eventRepeatFrequency').onchange=refresh;$('eventSheet').addEventListener('change',refresh);$('practiceWeekdays').addEventListener('click',()=>queueMicrotask(refresh));
 return {refresh,reset,handles,save,dates};
})();
