/* Athlete-first tournament recording. Every action is authorized by the server. */
window.WMMatchVideo = (() => {
 'use strict';
 const $=id=>document.getElementById(id), E=v=>esc(String(v??''));
 let generation=0, replay=null, busy=false;
 const bookButtons=['matchBookBtn','clipboardMatchBookBtn','matchBookRoomBtn'];
 function bookAccess(allowed=false){for(const id of bookButtons)$(id)?.classList.toggle('hidden-role',!isStaff&&!allowed);window.WMClipboard?.sync();}
 const context=()=>({user:session?.user?.id,team:activeTeam?.id});
 const valid=c=>c.user&&c.team&&c.user===session?.user?.id&&c.team===activeTeam?.id&&!managedLogin&&!document.body.classList.contains('kiosk-locked')&&!document.querySelector('#appLockOverlay:not(.hidden)');
 async function rpc(action,data={}) { const c=context();if(!valid(c))throw Error('Open your personal team account.');const r=await client.rpc('video_match_request',{p_action:action,p_data:{...data,team_id:c.team}});if(!valid(c))throw Error('Your account or team changed.');if(r.error)throw Error(r.error.message);return r.data; }
 function reset(){generation++;replay?.querySelector('video')?.pause();replay?.remove();replay=null;document.querySelectorAll('[data-video-profile]').forEach(x=>x.remove());$('videoAssignmentsBtn')?.remove();$('lockerMatchBookBtn')?.remove();bookAccess();}
 function button(text,run){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=async()=>{b.disabled=true;try{await run();}catch(e){message(e.message,true);}finally{b.disabled=false;}};return b;}
 async function sync(){const g=++generation;try{const data=await rpc('assignments');if(g!==generation)return;bookAccess(data.can_scorebook===true);
  let entry=$('lockerMatchBookBtn');if(data.can_scorebook&&!entry){entry=button('Match Book · score & record',scorebook);entry.id='lockerMatchBookBtn';entry.className='wide secondary mv-entry';$('lockerGoalsTab')?.parentElement?.after(entry);}if(entry)entry.hidden=!data.can_scorebook;
  let b=$('videoAssignmentsBtn');if(!b){b=button('Record team matches',scorebook);b.id='videoAssignmentsBtn';$('tournamentDayBtn')?.parentElement?.append(b);}if(b)b.hidden=!data.can_scorebook;
 }catch{if(g!==generation)return;$('videoAssignmentsBtn')?.remove();$('lockerMatchBookBtn')?.remove();bookAccess();}}
 async function scorebook(){const data=await rpc('assignments');if(!data.can_scorebook)throw Error('Your coach needs to give this personal account recorder access.');closeSheets();const box=sheet('Match Book');box.innerHTML='<p>Score and record your assigned team matches. Athletes and student managers use their own accounts.</p>';
  if(data.can_record_test)box.append(button('Test scorebook',test));else box.insertAdjacentHTML('beforeend','<p>Your coach can assign a match to enable your camera test.</p>');
  renderBouts(box,data.bouts);if(data.can_manage)box.append(button('Set event rules & recorder access',manage));
  const c=context();try{const draft=JSON.parse(localStorage.getItem('wm-match-draft-v1:'+c.user+':'+c.team)||'null');if(data.can_record_test&&draft?.owner===c.user&&draft?.team_id===c.team&&draft?.data?.video_test)box.append(button('Resume test scorebook',async()=>{await rpc('recorder_test');replay?.remove();replay=null;await WMMatch.openVideo(draft);}));}catch{}
 }
 async function test(){if(window.WMVideoPilot?.active())throw Error('Stop and save your current recording first.');const row=await rpc('recorder_test');replay?.remove();replay=null;await WMMatch.openVideo(row);$('vpPanel')?.scrollIntoView({block:'start'});}

 function sheet(title){replay?.remove();const box=document.createElement('section');box.className='vp-replay';box.innerHTML=`<div><div class="vp-head"><h2>${E(title)}</h2><button type="button">Close</button></div><div class="mv-content"></div></div>`;box.querySelector('button').onclick=()=>{box.querySelector('video')?.pause();box.remove();replay=null;};document.body.append(box);replay=box;return box.querySelector('.mv-content');}

 function renderBouts(box,bouts){if(!bouts.length){box.insertAdjacentHTML('beforeend','<p>No upcoming bouts ready to record. Your coach sets the event rules and assigns recorders; a linked parent controls recording permission.</p>');return;}
  for(const b of bouts){const card=document.createElement('article');card.className='vp-take';card.innerHTML=`<h3>${E(b.athlete_name)}</h3><p>${E(b.event_name)} · Bout ${E(b.bout_number)} · Mat ${E(b.mat||'pending')}</p><p>vs ${E(b.opponent||'Opponent pending')}</p><p class="fine">Coach entered · ${E(new Date(b.updated_at).toLocaleString())}</p>`;card.append(button('Score & record match',()=>start(b.id)));box.append(card);}}
 async function start(boutId){if(busy)return;if(window.WMVideoPilot?.active())throw Error('Stop and save the current video first.');busy=true;try{const row=await rpc('begin',{bout_id:boutId});replay?.remove();replay=null;await WMMatch.openVideo(row);if(WMMatch.videoSnapshot()?.id!==row.id)return;await WMVideoPilot.quickStart();$('vpPanel')?.scrollIntoView({block:'start'});}finally{busy=false;}}
 async function profile(athleteId,host='athleteViewSheet'){const g=generation,c=context();try{const data=await rpc('athlete',{athlete_id:athleteId});if(g!==generation||!valid(c))return;const root=$(host);if(!root||root.classList.contains('hidden'))return;root.querySelector('[data-video-profile]')?.remove();const box=document.createElement('section');box.className='vp-panel';box.dataset.videoProfile=athleteId;box.innerHTML='<h3>Match videos</h3>';root.append(box);
   renderBouts(box,data.bouts);
   if(data.recordings.length){for(const r of data.recordings){const card=document.createElement('article');card.className='vp-take';card.innerHTML=`<b>${E(r.label)} · Bout ${E(r.bout_number)}</b><p>vs ${E(r.opponent)}${r.partial?' · Partial recording':''}</p>`;card.append(button('Watch / download',()=>play(r.id)));if(data.can_set_permission||data.can_manage)card.append(button('Remove shared video',async()=>{if(!confirm('Remove access to this shared video? Downloads already saved by family cannot be recalled.'))return;await rpc('remove',{id:r.id});await profile(athleteId,host);}));box.append(card);}}
   else box.insertAdjacentHTML('beforeend','<p>No uploaded videos yet. Recordings waiting for service stay on the recorder’s device.</p>');
   if(data.can_set_permission){const label=document.createElement('label');label.className='vp-check';label.innerHTML=`<input type="checkbox" ${data.permission===true?'checked':''}>Allow match recording and private athlete/family sharing`;const input=label.querySelector('input');input.onchange=async()=>{input.disabled=true;try{await rpc('permission',{athlete_id:athleteId,allowed:input.checked});await profile(athleteId,host);}catch(e){input.checked=!input.checked;message(e.message,true);}finally{input.disabled=false;}};box.append(label);box.insertAdjacentHTML('beforeend','<p class="fine">Turning this off blocks new recordings and shared access. A restriction from either linked parent takes priority.</p>');}
  }catch{/* Pilot not enabled or this viewer has no access: do not expose the entry point. */}}
 async function urls(id,download=false){const row=await rpc('playback',{id}),c=context();const [video,timeline]=await Promise.all([client.storage.from(row.bucket).createSignedUrl(row.video_path,120,download?{download:'Match-video'}:undefined),client.storage.from(row.bucket).createSignedUrl(row.timeline_path,120)]);if(!valid(c))throw Error('Account changed.');if(video.error||timeline.error)throw Error('The saved video is temporarily unavailable. Try again.');return{video:video.data.signedUrl,timeline:timeline.data.signedUrl};}
 async function verifyCloud(id){const links=await urls(id);await new Promise((resolve,reject)=>{const v=document.createElement('video');v.muted=true;v.playsInline=true;const timer=setTimeout(()=>done(Error('Cloud playback could not be checked. Keep the device copy.')),20000);const done=e=>{clearTimeout(timer);v.removeAttribute('src');v.load();e?reject(e):resolve();};v.onloadeddata=()=>done();v.onerror=()=>done(Error('Cloud playback could not be checked. Keep the device copy.'));v.src=links.video;v.load();});return true;}
 async function play(id){const links=await urls(id),box=sheet('Match video'),c=context();box.innerHTML='<div class="vp-stage"><video controls playsinline preload="metadata"></video><div class="mv-replay-score"></div></div><p class="fine">Private family video. Download links expire after two minutes.</p>';const video=box.querySelector('video');video.src=links.video;let retrying=false;video.onerror=async()=>{if(retrying||!valid(c)||!box.isConnected)return;retrying=true;const at=video.currentTime,paused=video.paused;try{const fresh=await urls(id);if(!valid(c)||!box.isConnected)return;video.onloadedmetadata=()=>{video.currentTime=at;if(!paused)video.play().catch(()=>{});};video.src=fresh.video;video.load();}catch{box.insertAdjacentHTML('beforeend','<p>Playback access expired or was removed. Reopen this video to check access.</p>');}};box.append(button('Download video',async()=>{const fresh=await urls(id,true);if(!valid(c))return;const a=document.createElement('a');a.href=fresh.video;a.rel='noopener';a.target='_blank';a.click();}));
  try{const response=await fetch(links.timeline);if(!response.ok)throw Error();const row=await response.json();if(!valid(c)||!box.isConnected)return;video.ontimeupdate=()=>{const s=WMVideoCore.stateAt(row.events||[],video.currentTime*1000+1);if(s)box.querySelector('.mv-replay-score').textContent=`${s.red_name} ${s.scores.red} · ${s.scores.other} ${s.other_name} · ${s.phaseLabel}`;};}catch{box.insertAdjacentHTML('beforeend','<p>Score timeline unavailable; original video is still playable.</p>');}}
 async function manage(){const data=await rpc('manage');const opts=rows=>rows.map(r=>[r.id,r.name]);const q=await WMOperations.dialog({title:'Tournament recording setup',description:'Use the event’s actual rules. Recording must be permitted by the event. Linked parents control private sharing.',fields:[{id:'event_id',label:'Tournament',options:opts(data.events)},{id:'preset',label:'Scoring rules',options:[['folkstyle','Folkstyle · custom event'],['freestyle','Freestyle'],['greco','Greco-Roman'],['beach','Beach']]},{id:'periods',label:'Period lengths in seconds, separated by commas',value:'120,120,120',required:true},{id:'breakSeconds',label:'Break between periods (seconds)',type:'number',value:'0'},{id:'takedown',label:'Takedown points',type:'number',value:'3'},{id:'permitted',label:'Event filming permission',options:[['no','Not confirmed / turn recording off'],['yes','Confirmed: recording is permitted']]},{id:'athlete_id',label:'Assign an athlete (optional)',options:[['','No assignment'],...opts(data.athletes)]},{id:'user_id',label:'Recorder · athlete, student manager or team member',options:opts(data.members)},{id:'assignment',label:'Assignment action',options:[['grant','Allow for 24 hours'],['revoke','Revoke access']]}],submit:'Save recording setup'});if(!q)return;await rpc('event_settings',{event_id:q.event_id,permitted:q.permitted==='yes',rules:{style:q.preset,periods:q.periods.split(',').map(Number),breakSeconds:Number(q.breakSeconds),takedown:Number(q.takedown)}});if(q.athlete_id)await rpc('assign',{event_id:q.event_id,athlete_id:q.athlete_id,user_id:q.user_id,revoke:q.assignment==='revoke'});message('Recording setup saved.');await sync();}
 function recorderControls(recording){let live=$('vpGoLive');if(!live&&$('vpStart')){live=button('Go live',()=>rpc('go_live'));live.id='vpGoLive';live.disabled=true;live.title='Live streaming is not connected yet';$('vpStart').parentElement.append(live);const p=document.createElement('p');p.id='vpLiveState';p.className='mv-live-state vp-status';p.setAttribute('role','status');$('vpStart').parentElement.after(p);}if($('vpLiveState')){$('vpLiveState').innerHTML=recording?'<span class="mv-record-dot" aria-hidden="true"></span> Recording on this device · not live':'Live streaming not connected';}}
 window.addEventListener('pagehide',reset);
 return{rpc,sync,reset,profile,start,scorebook,test,urls,verifyCloud,recorderControls};
})();
