/* 0.20.39. No vote choices in localStorage, telemetry, receipts or history. */
window.WMVoting=(()=>{
 let state=null,epoch=0;
 const el=id=>document.getElementById(id),E=v=>esc(String(v??'')),copy=v=>JSON.parse(JSON.stringify(v));
 const alive=s=>s===state&&s.epoch===epoch&&s.uid===session?.user?.id&&s.team===activeTeam?.id&&!managedLogin&&!document.body.classList.contains('kiosk-locked');
 const field=(id,label,value='',type='text',attrs='')=>`<label>${E(label)}<input id="${id}" type="${type}" value="${E(value)}" ${attrs}></label>`;
 const area=(id,label,value='',max=4000)=>`<label>${E(label)}<textarea id="${id}" maxlength="${max}">${E(value)}</textarea></label>`;
 const choose=(id,label,rows,value='')=>`<label>${E(label)}<select id="${id}">${rows.map(([v,n])=>`<option value="${E(v)}" ${String(v)===String(value??'')?'selected':''}>${E(n)}</option>`).join('')}</select></label>`;
 const val=id=>el(id)?.value?.trim()||'',num=id=>val(id)===''?null:Number(val(id));
 const privacy='Choices are hidden from other app users, including the chair. Only combined results appear after closing. Database administrators and inferences from small or unanimous votes are outside this protection.';
 function close(){if(state)clearTimeout(state.timer);el('vbRoot')?.remove();el('vote039Sheet')?.classList.add('hidden');state=null;epoch++;}
 async function call(s,q){if(!alive(s))throw Error('Account or team changed. Reopen voting.');const {data,error}=await client.rpc('organization_governance',{p_request:{organization_id:s.org,...q}});if(!alive(s))throw Error('Account or team changed. Reopen voting.');if(error){const e=Error(error.message||'The server could not confirm this action.');e.code=error.code;throw e;}return data;}
 function note(s,message,bad=false){if(!alive(s))return;const n=el('vbStatus');if(n){n.textContent=message;n.classList.toggle('ops-error',bad);}}
 function shell(s,body,preserve=false){if(!alive(s))return;const sheet=el(s.host).closest('.sheet'),scroll=sheet?.scrollTop||0;el(s.host).innerHTML=`<section id="vbRoot" class="vb-root"><p id="vbStatus" role="status" aria-live="polite"></p>${body}</section>`;if(sheet)sheet.scrollTop=preserve?scroll:0;}
 async function open({org}){close();const s=state={org,epoch,uid:session?.user?.id,team:activeTeam?.id,host:'opsContent',screen:0};await list(s);}
 async function inbox(){if(!session?.user||managedLogin||document.body.classList.contains('kiosk-locked'))return;closeSheets();close();const s=state={org:null,epoch,uid:session.user.id,team:activeTeam?.id,host:'vote039Body',screen:0,inbox:true};openSheet('vote039Sheet');await inboxList(s);}
 async function inboxList(s){const ticket=++s.screen;clearTimeout(s.timer);shell(s,'<h3>My private ballots</h3><p>Loading…</p>');try{const rows=await call(s,{action:'ballot_inbox'});if(ticket!==s.screen)return;s.round=null;s.pending=null;shell(s,`<h3>My private ballots</h3><p>Ballots assigned to your personal account appear here.</p><button id="vbRefresh" class="secondary">Refresh</button>${rows.map(r=>`<article class="ops-card">${r.is_test?'<b class="vb-test">TEST BALLOT</b>':''}<h4>${E(r.motion)}</h4><p>${E(r.organization_name)} · ${E(r.status)} · ${r.submitted?'Vote recorded':'No vote recorded'}</p><button data-vb-open="${E(r.id)}" data-org="${E(r.organization_id)}">Open ballot</button></article>`).join('')||'<p>No ballots are assigned to this account.</p>'}`);el('vbRefresh').onclick=()=>inboxList(s);el('vbRoot').querySelectorAll('[data-vb-open]').forEach(b=>b.onclick=()=>{s.org=b.dataset.org;load(s,b.dataset.vbOpen);});}catch(e){note(s,e.message,true);}}
 async function list(s){if(s.inbox)return inboxList(s);const ticket=++s.screen;clearTimeout(s.timer);shell(s,'<h3>Private voting</h3><p>Loading saved ballots…</p>');try{const data=await call(s,{action:'ballot_context'});if(ticket!==s.screen)return;s.data=data;s.round=null;s.pending=null;shell(s,`<h3>Private voting</h3><p class="ops-sheet-note">${privacy}</p><div class="ops-actions">${data.meetings.length?'<button id="vbNew">+ New ballot</button>':''}<button id="vbRefresh" class="secondary">Refresh</button></div>${data.rounds.map(r=>`<article class="ops-card">${r.is_test?'<b class="vb-test">TEST BALLOT</b>':''}<h4>${E(r.motion)}</h4><p>${E(r.meeting_title)} · Round ${E(r.round_number)} · ${r.electorate==='board'?'Board':'Clubs'}</p><p>${E(r.status)}${r.result?' · '+E(label(r.result.outcome)):''}${r.my_ballot?.submitted?' · Your ballot is recorded':''}</p><button data-vb-open="${E(r.id)}" class="secondary">${r.my_ballot?.can_vote?'Vote':'Open round'}</button></article>`).join('')||'<div class="empty-card">No ballots are available. A meeting chair, secretary or organization administrator can prepare a round.</div>'}`);el('vbRefresh').onclick=()=>list(s);el('vbNew')?.addEventListener('click',()=>edit(s));el('vbRoot').querySelectorAll('[data-vb-open]').forEach(b=>b.onclick=()=>load(s,b.dataset.vbOpen));}catch(e){note(s,e.message,true);}}
 const label=o=>({passed:'Passed',not_passed:'Did not pass',no_quorum:'No quorum — no decision',no_decision:'No decision',new_round_required:'New round required under the recorded tie rule'})[o]||o;
 function policy(p={}){return `<dl class="vb-policy"><dt>Attendance quorum</dt><dd>${E(p.min_attendance??'Not set')}</dd><dt>Ballots required</dt><dd>${E(p.min_ballots??'Not set')}</dd><dt>Approval threshold</dt><dd>${E(p.comparison==='gt'?'More than':p.comparison==='gte'?'At least':'Not set')} ${E(p.numerator??'?')}/${E(p.denominator??'?')} of ${p.basis==='electorate'?'the entire electorate':'counted ballots'}</dd><dt>Abstentions</dt><dd>${E(p.abstentions||'Not set')}</dd><dt>Tie</dt><dd>${E(label(p.tie)||'Not set')}</dd></dl><p class="mt-text">${E(p.governing_rule||'Governing rule not recorded')}</p><p class="mt-text">Electronic-voting authority: ${E(p.electronic_authorization||'Not recorded')}</p>`;}
 function resultHTML(r){const t=r.totals||{};return `<section class="ops-card"><h4>${E(label(r.outcome))}</h4><div class="vb-counts"><p><b>${E(t.for??0)}</b>For</p><p><b>${E(t.against??0)}</b>Against</p><p><b>${E(t.abstain??0)}</b>Abstain</p></div><p>${E(r.ballots_cast)} ballots · ${E(r.attendance_count)} present · ${E(r.eligible_count)} electorate</p><p>Approval denominator: ${E(r.approval_denominator)}</p></section>`;}
 async function load(s,id){clearTimeout(s.timer);const ticket=++s.screen;s.editing=false;s.dirty=false;try{note(s,'Loading ballot…');const r=await call(s,{action:'ballot_detail',id});if(ticket!==s.screen)return;s.round=r;s.pending=null;render(s);}catch(e){note(s,e.message,true);}}
 function render(s,preserve=false){if(!alive(s))return;const r=s.round;clearTimeout(s.timer);shell(s,`<button id="vbBack" class="secondary">${s.inbox?'My ballots':'All rounds'}</button>${r.is_test?'<p class="vb-test"><b>TEST BALLOT</b> · Excluded from official organization records.</p>':''}<h3>${E(r.motion)}</h3><p>${E(r.meeting_title)} · Round ${E(r.round_number)} · ${r.electorate==='board'?'Board electorate':'Eligible attending clubs'}</p><p>Moved by ${E(r.mover||'Not recorded')} · Seconded by ${E(r.seconder||'Not recorded')}</p><p><b>${E(r.status.toUpperCase())}</b> · ${E(r.eligible_count)} eligible seats · ${E(r.attendance_count)} present</p><p class="ops-sheet-note">${privacy}</p>${r.result?resultHTML(r.result):r.status==='cancelled'?`<p>Cancelled: ${E(r.change_reason)}</p>`:'<p class="ops-sheet-note">Vote totals are hidden until this round closes.</p>'}
 ${r.my_ballot?`<section class="ops-card"><h4>Your ballot · ${E(r.my_ballot.label)}</h4>${r.my_ballot.submitted?'<p>Your ballot is recorded. Your choice is not displayed or changeable.</p>':r.my_ballot.can_vote?voteForm(): '<p>Voting is not open for this seat.</p>'}</section>`:''}
 <details class="ops-card"><summary>Rules for this round</summary>${policy(r.policy)}</details>
 ${r.can_manage?`<h4>Participation</h4><p class="ops-sheet-note">Shows who has submitted, never their choices. A delegate substitution keeps the club’s existing ballot status.</p><div class="vb-participants">${(r.participants||[]).map(p=>`<article class="ops-card"><b>${E(p.name)}</b><p>${E(p.delegate_name||'Unassigned')}${p.present?' · Present':' · Absent'} · <strong>${p.submitted?'Submitted':'Not submitted'}</strong></p>${r.electorate==='affiliates'&&['open','draft'].includes(r.status)?`<button data-vb-delegate="${E(p.entity_id)}" class="secondary">Change delegate</button>`:''}${r.is_test&&r.status==='open'&&!p.delegate_user_id&&!p.submitted?`<button data-vb-simulate="${E(p.entity_id)}" class="secondary">Simulate test vote</button>`:''}</article>`).join('')}</div><div class="ops-actions">${r.status==='draft'?'<button id="vbEdit">Edit draft</button><button id="vbOpen">Review & open voting</button>':''}${r.status==='open'?'<button id="vbClose">Close voting & reveal totals</button>':''}${['draft','open'].includes(r.status)?'<button id="vbCancel" class="secondary">Cancel round</button>':''}${['closed','cancelled'].includes(r.status)?'<button id="vbNewRound" class="secondary">New round / amendment</button>':''}</div>`:''}<button id="vbRefresh" class="secondary">Refresh status</button>`,preserve);
  el('vbBack').onclick=()=>list(s);el('vbRefresh').onclick=()=>load(s,r.id);el('vbEdit')?.addEventListener('click',()=>edit(s,r));el('vbNewRound')?.addEventListener('click',()=>edit(s,r,true));el('vbOpen')?.addEventListener('click',()=>review(s));el('vbClose')?.addEventListener('click',()=>action(s,'ballot_close','Close this round and reveal only its combined results? This cannot be reopened.'));
  el('vbCancel')?.addEventListener('click',()=>cancel(s));bindVote(s);el('vbRoot').querySelectorAll('[data-vb-delegate]').forEach(b=>b.onclick=()=>delegate(s,b.dataset.vbDelegate));el('vbRoot').querySelectorAll('[data-vb-simulate]').forEach(b=>b.onclick=()=>simulate(s,b.dataset.vbSimulate));
  if(r.status==='open')poll(s);
 }
 function poll(s){const r=s.round;s.timer=setTimeout(async()=>{if(!alive(s)||s.editing)return;try{const fresh=await call(s,{action:'ballot_detail',id:r.id});if(!alive(s)||s.editing||s.round?.id!==r.id)return;if(document.querySelector('#vbVoteForm input:checked')&&fresh.status==='open'&&!fresh.my_ballot?.submitted){s.round=fresh;poll(s);return;}s.round=fresh;render(s,true);}catch(e){note(s,'Status could not refresh. '+e.message,true);}},10000);
 }
 function voteForm(test=false){return `<form id="vbVoteForm"><fieldset><legend>${test?'Simulated test choice':'Choose your vote'}</legend>${[['for','For'],['against','Against'],['abstain','Abstain']].map(([v,n])=>`<label class="ops-check"><input type="radio" name="vbChoice" value="${v}" required>${n}</label>`).join('')}</fieldset><p class="ops-sheet-note">One ballot per seat. A submitted choice cannot be changed.</p><button type="submit">${test?'Submit simulated vote':'Submit private ballot'}</button></form>`;}
 function bindVote(s,entity=null){el('vbVoteForm')?.addEventListener('submit',async ev=>{ev.preventDefault();const form=ev.currentTarget;const choice=form.querySelector('input:checked')?.value;if(!choice||!confirm(entity?'Submit this simulated test vote?':'Submit your private ballot? It cannot be changed afterward.'))return;const q={action:entity?'ballot_test_cast':'ballot_cast',id:s.round.id,choice,...(entity?{entity_id:entity}:{})};form.reset();form.querySelector('button').disabled=true;try{const out=await call(s,q);q.choice=null;if(!out?.recorded)throw Error('Vote not confirmed.');s.editing=false;await load(s,s.round.id);note(s,'Ballot recorded. Your choice is not included in the receipt.');}catch(e){q.choice=null;s.editing=false;note(s,'Your vote could not be confirmed. Refresh status before trying again. '+e.message,true);if(form.isConnected)form.querySelector('button').disabled=false;}});}
 function simulate(s,id){s.editing=true;clearTimeout(s.timer);const p=s.round.participants.find(p=>p.entity_id===id);shell(s,`<button id="vbBack" class="secondary">Back</button><p class="vb-test">TEST SIMULATION · ${E(p.name)}</p><p>This is an unassigned test seat. You are trying the voting workflow, not voting for a real club.</p>${voteForm(true)}`);el('vbBack').onclick=()=>load(s,s.round.id);bindVote(s,id);}
 async function write(s,q){const sig=JSON.stringify(q);if(s.pending&&s.pending.sig!==sig)throw Error('A previous action is unconfirmed. Retry it unchanged or reload the saved round first.');if(!s.pending)s.pending={sig,q:{...q,request_id:crypto.randomUUID()}};try{const out=await call(s,s.pending.q);s.pending=null;return out;}catch(e){if(/^[0-9A-Z]{5}$/.test(e.code||''))s.pending=null;throw e;}}
 async function action(s,action,question,extra={}){if(question&&!confirm(question))return;try{note(s,'Saving…');const out=await write(s,{action,id:s.round.id,revision:s.round.revision,...extra});await load(s,out.id);}catch(e){note(s,e.message,true);}}
 async function context(s){s.data=await call(s,{action:'ballot_context'});return s.data;}
 async function edit(s,old=null,next=false){clearTimeout(s.timer);s.editing=true;try{await context(s);if(!alive(s))return;const p=old?.policy||{};s.pending=null;s.dirty=false;let selected=old?.participants||[];const meeting=old?.meeting_id||s.data.meetings[0]?.id;if(!meeting){note(s,'A scheduled or active meeting is required.',true);return;}
 shell(s,`<button id="vbEditBack" class="secondary">Back</button><h3>${next?'New round / amendment':old?'Edit draft':'New private ballot'}</h3><form id="vbSetup"><div class="gs-grid">${choose('vbMeeting','Meeting',s.data.meetings.map(m=>[m.id,(m.is_test?'TEST · ':'')+m.title]),meeting)}${choose('vbBody','Electorate',[['board','Board'],['affiliates','Eligible attending clubs']],old?.electorate||'board')}</div>${area('vbMotion','Motion / question',old?.motion||'',8000)}<div class="gs-grid">${field('vbMover','Mover',old?.mover||'')}${field('vbSeconder','Seconder',old?.seconder||'')}</div>${next?area('vbReason','Reason for amendment / new round','',2000):''}<h4>Electorate and delegates</h4><p class="ops-sheet-note">Review eligible seats from the meeting roll call. For a live club ballot, membership and voting eligibility must also be confirmed in Affiliate directory. One personal account can represent one seat per round.</p><div id="vbRoster"></div><h4>Governing rules</h4><button id="vbExample" type="button" class="secondary hidden">Use sample TEST rules</button>${area('vbRule','Rule establishing quorum, majority and tie handling',p.governing_rule||'')}${area('vbAuthority','Authority permitting electronic / secret voting',p.electronic_authorization||'')}<div class="gs-grid">${field('vbAttendance','Attendance required for quorum',p.min_attendance??'','number','min="1" max="9999"')}${field('vbBallots','Submitted ballots required for a decision',p.min_ballots??'','number','min="1" max="9999"')}${choose('vbPreset','Approval rule',[['','Choose explicitly'],['majority','More than half'],['two_thirds','At least two thirds'],['unanimous','All'],['custom','Custom fraction']],old?'custom':'')}${choose('vbComparison','Threshold comparison',[['','Choose'],['gt','More than'],['gte','At least']],p.comparison||'')}${field('vbNumerator','Threshold numerator',p.numerator??'','number','min="1" max="9999"')}${field('vbDenominator','Threshold denominator',p.denominator??'','number','min="1" max="9999"')}${choose('vbBasis','Threshold denominator',[['','Choose'],['votes_cast','Counted ballots'],['electorate','Entire snapshotted electorate']],p.basis||'')}${choose('vbAbstentions','Abstentions',[['','Choose'],['exclude','Exclude from counted ballots'],['include','Include in denominator']],p.abstentions||'')}${choose('vbTie','If For and Against tie',[['','Choose'],['not_passed','Motion does not pass'],['no_decision','No decision'],['new_round','Require a new round']],p.tie||'')}</div><p class="ops-sheet-note">Zero ballots, insufficient quorum or no For/Against votes cannot produce a passed motion. New rounds are created explicitly.</p><button id="vbSave" type="submit">Save draft</button></form>`);
 const roster=()=>{const m=s.data.meetings.find(m=>m.id===val('vbMeeting')),kind=val('vbBody')==='board'?'board':'affiliate';el('vbExample').classList.toggle('hidden',!m?.is_test);const rows=(m?.roll||[]).filter(r=>r.kind===kind&&r.eligible&&(kind==='board'||r.present));el('vbRoster').innerHTML=rows.map(r=>{const prior=selected.find(p=>p.entity_id===r.id);return `<article class="ops-card" data-vb-seat="${E(r.id)}"><label class="ops-check"><input type="checkbox" data-vb-selected ${(!old||prior)?'checked':''}>${E(r.name)} · ${r.present?'Present':'Absent'}</label>${kind==='affiliate'?choose('vbPerson-'+r.id,'Designated adult delegate',[['',m?.is_test?'Unassigned test seat · simulate votes':'Not assigned'],...s.data.directory.map(p=>[p.id,p.name])],prior?.delegate_user_id||''):'<p>Board vote belongs to this person’s own account.</p>'}</article>`;}).join('')||'<p>No eligible seats found. Return to the meeting’s Roll call & quorum section and review attendance and eligibility first.</p>';};roster();el('vbMeeting').disabled=!!old;el('vbMeeting').onchange=()=>{selected=[];roster();};el('vbBody').onchange=()=>{selected=[];roster();};
 el('vbPreset').onchange=()=>{const choice=val('vbPreset');if(choice==='custom'||!choice)return;el('vbNumerator').value=choice==='two_thirds'?2:1;el('vbDenominator').value=choice==='unanimous'?1:choice==='two_thirds'?3:2;el('vbComparison').value=choice==='majority'?'gt':'gte';};el('vbBasis').onchange=()=>{if(val('vbBasis')==='electorate')el('vbAbstentions').value='include';};el('vbExample').onclick=()=>{el('vbRule').value='TEST ONLY: one present seat and one submitted ballot; more than half of For/Against votes; ties do not pass.';el('vbAuthority').value='TEST ONLY: workflow practice, no official decision.';el('vbAttendance').value=el('vbBallots').value=el('vbNumerator').value='1';el('vbDenominator').value='2';el('vbComparison').value='gt';el('vbBasis').value='votes_cast';el('vbAbstentions').value='exclude';el('vbTie').value='not_passed';s.dirty=true;};el('vbSetup').oninput=()=>{s.dirty=true;note(s,'Unsaved draft changes.');};el('vbEditBack').onclick=()=>{if(!s.dirty||confirm('Discard these unsaved draft changes?'))old?load(s,old.id):list(s);};
 el('vbSetup').onsubmit=async ev=>{ev.preventDefault();const participants=[...el('vbRoster').querySelectorAll('[data-vb-seat]')].filter(n=>n.querySelector('[data-vb-selected]').checked).map(n=>({entity_id:n.dataset.vbSeat,delegate_user_id:val('vbBody')==='board'?n.dataset.vbSeat:val('vbPerson-'+n.dataset.vbSeat)||null}));const q={action:'ballot_save',id:old&&!next?old.id:null,revision:old&&!next?old.revision:null,meeting_id:val('vbMeeting'),prior_id:next?old.id:null,change_reason:val('vbReason'),motion:val('vbMotion'),mover:val('vbMover'),seconder:val('vbSeconder'),electorate:val('vbBody'),participants,policy:{governing_rule:val('vbRule'),electronic_authorization:val('vbAuthority'),min_attendance:num('vbAttendance'),min_ballots:num('vbBallots'),numerator:num('vbNumerator'),denominator:num('vbDenominator'),comparison:val('vbComparison'),basis:val('vbBasis'),abstentions:val('vbAbstentions'),tie:val('vbTie')}};el('vbSave').disabled=true;try{note(s,'Saving draft…');const out=await write(s,q);s.dirty=false;await load(s,out.id);}catch(e){note(s,'Draft not confirmed. '+e.message,true);}finally{if(el('vbSave'))el('vbSave').disabled=false;}};
 }catch(e){note(s,e.message,true);}}
 function review(s){s.editing=true;clearTimeout(s.timer);const r=s.round;shell(s,`<button id="vbBack" class="secondary">Back</button><h3>Review before opening</h3>${r.is_test?'<p class="vb-test">TEST ROUND · No official decision</p>':''}<p>${E(r.motion)}</p><p>${E(r.eligible_count)} seats · ${E(r.attendance_count)} present</p>${policy(r.policy)}<p class="ops-sheet-note">Opening freezes the motion, electorate, attendance and rules for this round. Club delegate substitutions keep the same single ballot.</p><form id="vbReview"><label class="ops-check"><input id="vbRulesConfirmed" type="checkbox" required>I confirm the recorded rules and authority permit this round${r.is_test?' for testing':''}.</label><label class="ops-check"><input id="vbDelegatesConfirmed" type="checkbox" required>I reviewed the electorate and explicitly approve these adult delegate assignments${r.is_test?' / unassigned test seats':''}.</label><button>Open voting</button></form>`);el('vbBack').onclick=()=>load(s,r.id);el('vbReview').onsubmit=ev=>{ev.preventDefault();action(s,'ballot_open',null,{confirm_rules:el('vbRulesConfirmed').checked,confirm_delegates:el('vbDelegatesConfirmed').checked});};}
 async function delegate(s,id){s.editing=true;clearTimeout(s.timer);try{await context(s);const p=s.round.participants.find(p=>p.entity_id===id);shell(s,`<button id="vbBack" class="secondary">Back</button><h3>Delegate · ${E(p.name)}</h3><p>${p.submitted?'This club has already voted. Changing its delegate will not allow another ballot.':'Only the new designated delegate will be able to vote.'}</p><form id="vbDelegateForm">${choose('vbDelegate','Adult personal account',[['','Choose'],...s.data.directory.map(p=>[p.id,p.name])],p.delegate_user_id)}<label class="ops-check"><input id="vbAdultConfirm" type="checkbox" required>I confirm this adult appointment for the club.</label><button>Save delegate</button></form>`);el('vbBack').onclick=()=>load(s,s.round.id);el('vbDelegateForm').onsubmit=ev=>{ev.preventDefault();action(s,'ballot_substitute',null,{entity_id:id,delegate_user_id:val('vbDelegate'),confirm_delegates:el('vbAdultConfirm').checked});};}catch(e){note(s,e.message,true);}}
 function cancel(s){s.editing=true;clearTimeout(s.timer);shell(s,'<button id="vbBack" class="secondary">Back</button><h3>Cancel round</h3><p>A cancelled round cannot reopen. Its choice totals will not be published.</p><form id="vbCancelForm">'+area('vbCancelReason','Cancellation reason','',2000)+'<button>Cancel round</button></form>');el('vbBack').onclick=()=>load(s,s.round.id);el('vbCancelForm').onsubmit=ev=>{ev.preventDefault();action(s,'ballot_cancel','Cancel this voting round?',{reason:val('vbCancelReason')});};}
 const sheet=document.createElement('section');sheet.id='vote039Sheet';sheet.className='sheet ops-sheet hidden';sheet.setAttribute('role','dialog');sheet.setAttribute('aria-modal','true');sheet.innerHTML='<div class="sheet-head"><h2>Private voting</h2><button id="vbSheetClose" class="icon-close" aria-label="Close voting">×</button></div><div id="vote039Body"></div>';document.body.appendChild(sheet);el('vbSheetClose').onclick=close;
 const entry=document.createElement('button');entry.className='wide secondary';entry.id='myPrivateBallots';entry.textContent='My private ballots';entry.onclick=inbox;el('personalAccountProfileCard')?.after(entry);
 document.addEventListener('click',ev=>{const s=state;if(!s?.dirty||!alive(s)||el('vbRoot')?.contains(ev.target))return;if(!confirm('Discard these unsaved ballot setup changes?')){ev.preventDefault();ev.stopImmediatePropagation();}else s.dirty=false;},true);
 window.addEventListener('beforeunload',ev=>{if(state?.dirty){ev.preventDefault();ev.returnValue='';}});
 return {open,inbox,close,resultHTML};
})();
