/* Profile-to-profile consent is independent of team membership. The server owns every gate. */
window.WMProfileChat=(()=>{
 'use strict';
 const $=id=>document.getElementById(id),E=v=>esc(String(v??''));
 let epoch=0,owner='',screen=0,rows=[],chat=null,messages=[],more=false,busy=false,last=0,polling=false;
 const drafts=new Map();
 const allowed=()=>!!session?.user?.id&&!managedLogin&&!document.body.classList.contains('kiosk-locked')&&!document.querySelector('#appLockOverlay:not(.hidden)');
 const sheet=document.createElement('section');sheet.id='profileChatsSheet';sheet.className='sheet hidden';sheet.setAttribute('role','dialog');sheet.setAttribute('aria-modal','true');sheet.setAttribute('aria-label','Profile chats');
 sheet.innerHTML='<div class="sheet-head"><h2>Profile chats</h2><button type="button" class="icon-close" data-close-profile-chat aria-label="Close profile chats">×</button></div><p id="profileChatStatus" role="status" aria-live="polite"></p><div id="profileChatBody"></div>';document.body.append(sheet);
 sheet.querySelector('[data-close-profile-chat]').onclick=()=>closeSheets();
 const note=s=>$('profileChatStatus').textContent=s;
 function reset(){epoch++;screen++;owner='';rows=[];chat=null;messages=[];drafts.clear();more=false;busy=false;last=0;$('profileChatBody').replaceChildren();note('');sheet.classList.add('hidden');badges();}
 const token=()=>({e:epoch,u:session?.user?.id,s:screen});
 const valid=(t,visible=false)=>allowed()&&t.e===epoch&&t.u===session?.user?.id&&(!visible||(t.s===screen&&!sheet.classList.contains('hidden')));
 async function call(action,data={},t=token()){if(!valid(t))throw Error('Unlock the app and use your personal account.');const r=await client.rpc('profile_connections_request',{p_action:action,p_data:data});if(!valid(t))throw Error('Account changed. Reopen profile chats.');if(r.error)throw Error(r.error.message);return r.data;}
 function syncOwner(){if(owner!==session?.user?.id){reset();owner=session?.user?.id||'';}}
 function unread(){return allowed()&&owner===session?.user?.id?rows.reduce((n,r)=>n+(r.unread||0)+(r.needs_response?1:0)+(r.needs_parent_review?1:0),0):0;}
 function badges(){document.querySelectorAll('[data-profile-chats]').forEach(b=>b.textContent='Profile chats'+(unread()?' ('+unread()+')':''));if(window.wrestlingManagerSignInReady)updateBottomNavBadges();}
 const title=c=>c.guardian_mirror?`${c.name_a} ↔ ${c.name_b}`:c.my_profile===c.profile_a?c.name_b:c.name_a;
 const reason=c=>c.can_send?'Chat accepted':c.reason||'Open conversation';
 async function refresh(){if(!allowed())return;syncOwner();const t=token(),out=await call('list',{},t);if(!valid(t))return;rows=Array.isArray(out)?out:[];last=Date.now();badges();}
 function inbox(){chat=null;messages=[];$('profileChatBody').innerHTML='<p class="fine">Chat requests and accepted conversations across teams. Parents can review their athletes’ chats here. Alerts appear in this inbox.</p><button type="button" class="secondary" data-chat-refresh>Refresh</button><div class="profile-chat-list">'+(rows.map(c=>`<button type="button" class="profile-chat-row secondary" data-chat-open="${E(c.id)}"><b>${E(title(c))}</b><span>${E(c.needs_response?'Accept or deny chat request':c.needs_parent_review?'Parent approval needed':reason(c))}</span><small>${c.guardian_mirror?'Parent mirror · ':''}${c.unread?E(c.unread)+' unread':''}</small></button>`).join('')||'<p>No profile chats yet. Open a profile you follow—or someone who follows you—to request a chat.</p>')+'</div>';}
 async function open(id){if(!allowed())return message('Unlock the app and use your personal account.',true);syncOwner();screen++;openSheet(sheet.id);note('Loading profile chats…');const t=token();try{if(id)await conversation(id,t);else{await refresh();if(valid(t,true)){inbox();note('');}}}catch(e){if(valid(t,true))note(e.message);}}
 function saveDraft(){if(chat&&$('profileChatText')){const prior=drafts.get(chat.id)||{};if(prior.body!==$('profileChatText').value)drafts.set(chat.id,{body:$('profileChatText').value,client_id:crypto.randomUUID()});}}
 function draw(){const c=chat;if(!c)return;const old=$('profileChatText'),focused=old===document.activeElement,selection=old?[old.selectionStart,old.selectionEnd]:null;
  $('profileChatBody').innerHTML=`<button type="button" class="secondary" data-chat-inbox>‹ All profile chats</button><h3>${E(title(c))}</h3><p>${E(reason(c))}</p>${c.guardian_mirror?'<p class="privacy-note">Parent mirror · read-only. Your permission is separate from the recipient accepting the chat.</p>':''}<div class="wp-actions">${c.participant&&c.incoming&&['pending','denied'].includes(c.status)?`<button type="button" data-chat-action="accept">Accept chat</button>${c.status==='pending'?'<button type="button" class="secondary" data-chat-action="deny">Deny chat</button>':''}`:''}${c.participant&&!c.incoming&&c.status==='pending'?'<button type="button" class="secondary" data-chat-action="withdraw">Withdraw request</button>':''}</div>${c.participant&&c.status==='accepted'?`<label class="toggle-row"><span><b>Allow this chat</b><small>Acceptance stays saved. Either person can stop messages here.</small></span><input type="checkbox" data-chat-permission ${c.my_allowed?'checked':''}></label>`:''}${(c.guardians||[]).filter(g=>g.can_manage).map(g=>`<section class="wp-panel"><h4>${E(g.name)} · your parent permission</h4><p>${g.my_choice===true?'You allow this chat.':g.my_choice===false?'You stopped this chat.':'Choose whether to allow this chat.'} Any linked parent’s restriction takes priority.</p><div class="wp-actions"><button type="button" data-chat-guardian="${E(g.profile_id)}" data-allow="true">Allow chat</button><button type="button" class="secondary" data-chat-guardian="${E(g.profile_id)}" data-allow="false">Stop chat</button></div></section>`).join('')}<div class="wp-actions"><button type="button" class="secondary" data-chat-refresh>Refresh</button>${more?'<button type="button" class="secondary" data-chat-older>Load older messages</button>':''}</div><div class="profile-chat-messages" role="log" aria-label="Conversation">${messages.map(m=>`<article class="profile-chat-message ${m.is_mine?'mine':''}"><small>${E(m.sender_name)} · ${E(new Date(m.created_at).toLocaleString())}${['medium','high'].includes(m.safety_level)?' · ⚑ Safety flag':''}</small><p>${E(m.body)}</p></article>`).join('')||'<p class="fine">No messages yet.</p>'}</div>${c.participant?`<form id="profileChatComposer"><label for="profileChatText">Message</label><textarea id="profileChatText" maxlength="4000" rows="3" ${c.can_send?'':'disabled'} placeholder="${c.can_send?'Write a message':'Chat permission is required'}">${E(drafts.get(c.id)?.body||'')}</textarea><button type="submit" ${c.can_send?'':'disabled'}>Send message</button></form>`:''}`;
  if(focused&&$('profileChatText')&&!$('profileChatText').disabled){$('profileChatText').focus({preventScroll:true});$('profileChatText').setSelectionRange(...selection);}
  $('profileChatComposer')?.addEventListener('submit',send);$('profileChatText')?.addEventListener('input',saveDraft);
 }
 async function conversation(id,t=token(),older=false){const first=messages[0],r=await call('read',{id,...(older&&first?{before_at:first.created_at,before_id:first.id}:{})},t);if(!valid(t,true))return;saveDraft();chat=r.chat;if(older)messages=[...(r.messages||[]),...messages];else messages=r.messages||[];more=!!r.more;draw();note('');refresh().catch(()=>{});}
 function freeze(on){sheet.querySelectorAll('button,input').forEach(b=>b.disabled=on);if(!on&&chat)draw();}
 async function change(action,data={}){if(busy||!chat)return;saveDraft();busy=true;const t=token(),id=chat.id;freeze(true);note('Saving…');try{await call(action,{id,revision:chat.revision,...data},t);if(valid(t,true))await conversation(id,t);}catch(e){if(valid(t,true))note(e.message);}finally{if(valid(t))busy=false;if(valid(t,true))freeze(false);}}
 async function send(e){e.preventDefault();if(busy||!chat?.can_send)return;saveDraft();const d=drafts.get(chat.id);if(!d?.body.trim())return;busy=true;const t=token(),id=chat.id;freeze(true);$('profileChatText').disabled=true;note('Sending…');try{await call('send',{id,...d},t);if(!valid(t,true))return;drafts.delete(id);$('profileChatText').value='';await conversation(id,t);}catch(e){if(valid(t,true))note(e.message+' Your message is kept here; retry uses the same message ID.');}finally{if(valid(t))busy=false;if(valid(t,true))freeze(false);}}
 sheet.addEventListener('change',e=>{if(e.target.matches('[data-chat-permission]'))change('preferences',{allowed:e.target.checked});});
 sheet.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||busy)return;try{if(b.hasAttribute('data-chat-inbox')){saveDraft();await open();}else if(b.dataset.chatOpen){saveDraft();screen++;await conversation(b.dataset.chatOpen);}else if(b.dataset.chatAction)await change(b.dataset.chatAction);else if(b.dataset.chatGuardian)await change('guardian',{profile_id:b.dataset.chatGuardian,allowed:b.dataset.allow==='true'});else if(b.hasAttribute('data-chat-older'))await conversation(chat.id,token(),true);else if(b.hasAttribute('data-chat-refresh')){if(chat)await conversation(chat.id);else await open();}}catch(err){note(err.message);}});
 async function connections(id,preview=false){const host=$('wpConnections');if(!host||preview)return;const t=token();try{const r=await call('connections',{profile_id:id},t);if(!valid(t)||!host.isConnected)return;host.innerHTML=['following','followed_by'].map(k=>`<details><summary>${k==='following'?'Following':'Followed by'} · ${(r[k]||[]).length}${(r[k]||[]).length===100?'+':''}</summary><div class="wp-actions">${(r[k]||[]).map(p=>`<button type="button" class="secondary" data-wp-open="${E(p.id)}">${E(p.name)}</button>`).join('')||'<p class="fine">No shared connections yet.</p>'}</div></details>`).join('')+'<p class="fine">Approved connections with shared profiles. Private and family-only connections stay private.</p>'; }catch(e){if(host.isConnected&&valid(t))host.textContent=e.message;}}
 async function pair(source,target,self){const host=$('wpChatConnection');if(!host)return;const t=token(),key=source+':'+target;host.dataset.pair=key;const current=()=>valid(t)&&host.isConnected&&host.dataset.pair===key;host.replaceChildren();if(!self){host.textContent='Use your own connected profile to request a chat.';return;}
  try{const r=await call('pair',{profile_id:source,target},t);if(!current())return;
   if(r.chat){const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=r.chat.needs_response?'Review chat request':'Open profile chat';b.onclick=()=>open(r.chat.id);host.append(b);return;}
   if(!r.can_request){host.textContent=r.reason||'Chat is unavailable for this connection.';return;}
   const b=document.createElement('button');b.type='button';b.textContent='Request chat';host.append(b);const n=document.createElement('p');n.className='fine';n.textContent='The recipient must accept. Athlete chats also need parent permission.';host.append(n);
   b.onclick=async()=>{if(b.disabled||!current())return;b.disabled=true;n.textContent='Requesting chat…';try{const c=await call('request',{profile_id:source,target},t);if(current()){await open(c.id);pair(source,target,self);}}catch(e){if(current()){n.textContent=e.message;b.disabled=false;}}};
  }catch(e){if(current())host.textContent=e.message;}}
 for(const anchor of ['communicationThreadList','personalAccountProfileCard']){const el=$(anchor);if(!el)continue;const b=document.createElement('button');b.type='button';b.className='wide secondary';b.dataset.profileChats='';b.textContent='Profile chats';b.onclick=()=>open();el.before(b);}
 setInterval(async()=>{if(!allowed()){if(owner)reset();return;}syncOwner();if(document.hidden||polling||busy||Date.now()-last<25000)return;polling=true;const t=token();try{await refresh();if(valid(t,true)){if(chat)await conversation(chat.id,t);else inbox();}}catch{}finally{polling=false;}},5000);
 return {open,reset,connections,pair,unread};
})();
